package com.e02.rootconsole;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.view.WindowManager;
import android.widget.*;
import android.content.*;
import java.io.*;
import java.net.*;
import java.security.SecureRandom;
import java.util.*;

public class MainActivity extends Activity {
 private static volatile boolean visible;
 static boolean visible(){return visible;}
 private LinearLayout panel,leftPanel;private FrameLayout rootFrame;private ScrollView remotePage;private RemotePanel remotePanel;private LinearLayout connectionPage,backgroundPage,settingsPage;private TextView updateStatus,updateNotice,networkStatus;private String installPromptId="";private Button mirrorTestButton;private TextView mirrorHint;private Spinner updateRoutes;private EditText routeCustom;private LinearLayout updateCard;private android.app.Dialog updateDialog;private final List<NetworkState.Address> networks=new ArrayList<>();private TextView rootState,sessionState,sessionError,output;private Spinner addresses;private RootOption rootToggle;
 private android.os.Handler sessionHandler=new android.os.Handler();private CheckBox overlayToggle,wirelessToggle,wiredToggle;private EditText computerIp;private TextView ipState;private Button applyIp;private String appliedIp="";private boolean wirelessEnabled;private boolean syncingAdb,adbBusy;
 private boolean rootAvailable;private Design.StatusText sessionHeading;private Button probeButton,startButton;private ConsoleServer server;private CommandRunner probeRunner;
 private String sessionUrl="",token="",bridgeSecret="";private boolean probing,dead,bridgeMode;private final List<String> ips=new ArrayList<>();
 private boolean endingAuthorization;private boolean startupStarted;private android.app.Dialog riskDialog;private Runnable phoneRefresh;private Button phoneButton,quitButton;private android.app.Dialog exitDialog,rootConsentDialog;private boolean rootConsentShown;private Button independentRootButton;private CheckBox keepAliveToggle,autoStartToggle;private boolean syncingRuntime,syncingChildren;private CheckBox statusBarToggle;private Button overlayPermissionButton,overlayCenterButton;private TextView keepAliveChildHint;private TextView pageTitle;private final List<Button> tabs=new ArrayList<>();
 private int dp(int n){return Design.dp(this,n);}
 private android.graphics.drawable.GradientDrawable surface(int color,int radius){return Design.surface(this,color,radius);}
 private TextView text(String s,int size){TextView t=Design.text(this,s,size);panel.addView(t);return t;}
 private Button button(String s,Runnable action){Button b=Design.button(this,s,action);Design.addButton(panel,b);return b;}
 private void card(LinearLayout l){Design.card(l);}
 private void statusBox(TextView t){t.setTextColor(Design.ACCENT);t.setPadding(0,dp(8),0,dp(8));}
 private void styleToggle(CompoundButton v){Design.toggle(v);}
 private LinearLayout column(){return Design.column(this);}
 private LinearLayout newCard(LinearLayout row,float weight){LinearLayout body=column();card(body);ScrollView scroll=Design.scroll(this,body);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,weight);if(row.getChildCount()>0)lp.leftMargin=dp(18);row.addView(scroll,lp);return body;}
 private Button actionRow(LinearLayout target,String a,Runnable fa,String b,Runnable fb){LinearLayout row=new LinearLayout(this);target.addView(row);Button first=Design.button(this,a,fa),second=Design.button(this,b,fb);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(54),1);p.setMargins(0,dp(6),dp(8),dp(6));row.addView(first,p);if(a.equals("启动命令回传"))Design.actionColor(first,true);if(b.equals("停止回传"))Design.actionColor(second,false);LinearLayout.LayoutParams secondParams=new LinearLayout.LayoutParams(0,dp(54),1);secondParams.setMargins(0,dp(6),0,dp(6));row.addView(second,secondParams);return first;}
 @Override public void onCreate(Bundle state){super.onCreate(state);
  android.content.res.Configuration readable=new android.content.res.Configuration(getResources().getConfiguration());readable.fontScale=Math.max(readable.fontScale,1.2f);getResources().updateConfiguration(readable,getResources().getDisplayMetrics());getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);getWindow().setStatusBarColor(Design.BG);getWindow().setNavigationBarColor(Design.BG);
  PhoneCompanion.attach(this);rootFrame=new FrameLayout(this);LinearLayout frame=new LinearLayout(this);frame.setPadding(dp(26),dp(22),dp(26),dp(24));frame.setBackgroundColor(Design.BG);rootFrame.addView(frame);setContentView(rootFrame);
  LinearLayout menu=column();menu.setPadding(0,0,dp(24),0);frame.addView(menu,new LinearLayout.LayoutParams(dp(240),-1));ImageView logo=new ImageView(this);logo.setImageResource(getResources().getIdentifier("ic_launcher","drawable",getPackageName()));logo.setScaleType(ImageView.ScaleType.FIT_CENTER);menu.addView(logo,new LinearLayout.LayoutParams(dp(82),dp(82)));TextView name=Design.text(this,"E02星匣",27);menu.addView(name);TextView edition=Design.text(this,"E02-Starbox\n"+UpdateService.installedName(this),16);menu.addView(edition);android.view.View spacer=new android.view.View(this);menu.addView(spacer,new LinearLayout.LayoutParams(1,dp(48)));
  LinearLayout content=column();frame.addView(content,new LinearLayout.LayoutParams(0,-1,1));LinearLayout top=new LinearLayout(this);top.setGravity(android.view.Gravity.CENTER_VERTICAL);pageTitle=Design.text(this,"连接",29);top.addView(pageTitle,new LinearLayout.LayoutParams(0,dp(64),1));phoneButton=Design.button(this,"手机助手 · 未连接",()->showPhone());top.addView(phoneButton,new LinearLayout.LayoutParams(dp(258),dp(54)));quitButton=Design.button(this,"退出程序及后台",this::requestExit);syncRuntimeOptions();LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(dp(244),dp(54));q.leftMargin=dp(14);top.addView(quitButton,q);content.addView(top);
  FrameLayout pages=new FrameLayout(this);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,0,1);pp.topMargin=dp(18);content.addView(pages,pp);connectionPage=column();pages.addView(connectionPage);backgroundPage=column();pages.addView(backgroundPage);backgroundPage.setVisibility(8);settingsPage=column();pages.addView(settingsPage);settingsPage.setVisibility(8);remotePage=new ScrollView(this);remotePage.setFillViewport(true);pages.addView(remotePage);remotePage.setVisibility(8);
  String[] names={"连接","远程","后台","设置"};for(int i=0;i<names.length;i++){final int index=i;Button tab=Design.button(this,names[i],()->selectPage(index));tabs.add(tab);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(-1,dp(66));mp.bottomMargin=dp(12);menu.addView(tab,mp);}android.view.View space=new android.view.View(this);menu.addView(space,new LinearLayout.LayoutParams(1,0,1));menu.addView(Design.text(this,"E02  /  停车后使用",17));selectPage(0);
  LinearLayout upper=new LinearLayout(this);connectionPage.addView(upper,new LinearLayout.LayoutParams(-1,0,1));panel=newCard(upper,1);text("ADB 连接",26);text("自动识别热点 / 外部 Wi-Fi，需先完成 Root 提权",18);
  LinearLayout net=new LinearLayout(this);panel.addView(net);addresses=new Spinner(this);net.addView(addresses,new LinearLayout.LayoutParams(0,dp(48),1));Button reload=Design.button(this,"刷新",()->{refresh();readAdb();});net.addView(reload,new LinearLayout.LayoutParams(dp(88),dp(48)));networkStatus=text("正在识别网络…",18);networkStatus.setMaxLines(2);networkStatus.setVisibility(8);
  text("允许连接的电脑 IPv4",19);computerIp=new EditText(this);computerIp.setSingleLine(true);Design.input(computerIp,"连接 → 电脑 IP",false);computerIp.setHint("例如 192.168.100.103");appliedIp=getSharedPreferences("connection",0).getString("computerIp","");computerIp.setText(appliedIp);LinearLayout ipRow=new LinearLayout(this);ipRow.setGravity(android.view.Gravity.CENTER_VERTICAL);panel.addView(ipRow);ipRow.addView(computerIp,new LinearLayout.LayoutParams(0,dp(52),1));applyIp=Design.button(this,"确认并应用",()->applyComputerIp());applyIp.setTextSize(18);LinearLayout.LayoutParams ipButton=new LinearLayout.LayoutParams(dp(145),dp(52));ipButton.leftMargin=dp(10);ipRow.addView(applyIp,ipButton);NumberPad.attach(computerIp);ipState=text("",16);computerIp.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence v,int a,int b,int c){}public void onTextChanged(CharSequence v,int a,int b,int c){updateIpState();}public void afterTextChanged(android.text.Editable v){}});updateIpState();
  networkStatus.setMaxLines(2);networkStatus.setEllipsize(android.text.TextUtils.TruncateAt.END);networkStatus.setTextSize(17);networkStatus.setPadding(0,dp(2),0,dp(2));
  wirelessToggle=new Design.AdbAction(this);wirelessToggle.setText("无线 ADB · 正在读取");wirelessToggle.setEnabled(false);panel.addView(wirelessToggle,new LinearLayout.LayoutParams(-1,dp(58)));wiredToggle=new Design.AdbAction(this);wiredToggle.setText("有线 ADB · 正在读取");wiredToggle.setEnabled(false);panel.addView(wiredToggle,new LinearLayout.LayoutParams(-1,dp(58)));wirelessToggle.setOnCheckedChangeListener((v,on)->{if(!syncingAdb)changeAdb(true,on);});wiredToggle.setOnCheckedChangeListener((v,on)->{if(!syncingAdb)changeAdb(false,on);});button("检测实际状态",()->readAdb());
  addresses.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,android.view.View v,int pos,long id){if(pos<networks.size()){networkStatus.setTextColor(Design.MUTED);networkStatus.setText(networks.get(pos).label());}}});
  panel=newCard(upper,1);sessionHeading=new Design.StatusText(this,"局域网命令回传",26);panel.addView(sessionHeading);text("电脑浏览器执行命令，查看返回结果",18);sessionState=text("尚未启动 · 网页端口 8875",18);sessionState.setTextColor(Design.ACCENT);sessionState.setPadding(0,dp(3),0,dp(3));sessionState.setLineSpacing(0,1f);sessionState.setTextIsSelectable(true);sessionState.setMaxLines(4);sessionError=text("",16);sessionError.setTextColor(Design.DANGER);sessionError.setVisibility(8);
  rootToggle=new RootOption();rootToggle.setText("允许本次网页执行 Root 命令");rootToggle.setAllowed(false);styleToggle(rootToggle);panel.addView(rootToggle);startButton=actionRow(panel,"启动命令回传",()->startServer(),"停止回传",()->stopServer());actionRow(panel,"复制连接信息",()->{if(sessionUrl.isEmpty()){Toast.makeText(this,"请先启动命令回传",0).show();return;}try{PhoneCompanion.copy(this,"session",sessionUrl+"\n连接码："+token,false);Toast.makeText(this,"已复制连接信息",0).show();}catch(Exception e){Toast.makeText(this,"复制失败",1).show();}},"查看诊断结果",()->Design.show(new android.app.AlertDialog.Builder(this).setTitle("连接诊断").setMessage(output.getText()+"\n"+AdbMaintenance.message).setPositiveButton("关闭",null)));
  leftPanel=column();card(leftPanel);LinearLayout.LayoutParams auth=new LinearLayout.LayoutParams(-1,dp(195));auth.bottomMargin=dp(18);connectionPage.addView(leftPanel,0,auth);panel=leftPanel;LinearLayout authHead=new LinearLayout(this);authHead.setGravity(android.view.Gravity.CENTER_VERTICAL);TextView authName=Design.text(this,"Root 提权",26);authHead.addView(authName,new LinearLayout.LayoutParams(-2,-2));rootState=Design.text(this,"状态：正在检测授权…",19);rootState.setMaxLines(2);rootState.setTextColor(Design.RED);LinearLayout.LayoutParams statusPlacement=new LinearLayout.LayoutParams(0,-2,1);statusPlacement.leftMargin=dp(24);authHead.addView(rootState,statusPlacement);panel.addView(authHead);
  LinearLayout actions=new LinearLayout(this);panel.addView(actions);independentRootButton=Design.button(this,"启用独立授权",()->showRootConsent());independentRootButton.setBackground(Design.feedback(this,Design.ACCENT,12));independentRootButton.setTextColor(Design.BG);actions.addView(independentRootButton,new LinearLayout.LayoutParams(dp(230),dp(54)));probeButton=Design.button(this,"重新检测 Root",()->probe());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(220),dp(54));bp.leftMargin=dp(16);actions.addView(probeButton,bp);Button end=Design.button(this,"结束提权",()->confirmEndAuthorization());LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(dp(180),dp(54));ep.leftMargin=dp(16);actions.addView(end,ep);TextView hint=Design.text(this,"首次启用需确认；结束提权后需重新确认。车机重启或后台停止后，会检查本机条件并尝试恢复。",18);hint.setSingleLine(true);hint.setEllipsize(android.text.TextUtils.TruncateAt.END);panel.addView(hint);output=new TextView(this);output.setText("等待连接诊断");
  SharedPreferences rprefs=getSharedPreferences("remote",0);if(rprefs.getInt("mode",0)==0&&rprefs.getString("origin","").equals("http://127.0.0.1:38765"))rprefs.edit().putString("origin","http://127.0.0.1:8875").apply();buildBackground();buildSettings();RootAccess.init(this);remotePanel=new RemotePanel(this);remotePage.addView(remotePanel);if(RiskNotice.accepted(this))startApprovedServices();else riskDialog=RiskNotice.show(this,this::startApprovedServices,this::exitAfterDecliningRisk);
 }
 private void startApprovedServices(){UpdateService.initialize(this);if(dead||startupStarted||!RiskNotice.accepted(this))return;if(!RuntimeSettings.open(this)){Toast.makeText(this,"无法保存运行设置，请检查星匣的存储空间后重试",1).show();return;}startupStarted=true;syncRuntimeOptions();RootAccess.resetRecovery();prepareBridge();refresh();getSharedPreferences("connection",0).edit().putBoolean("appActive",true).apply();startForegroundService(new Intent(this,ConsoleService.class));PhoneCompanion.attach(this);checkBridgeOnResume();sessionHandler.removeCallbacks(sessionTick);sessionHandler.post(sessionTick);if(RuntimeSettings.snapshot(this).keepAlive&&getSharedPreferences("connection",0).getBoolean("overlay",true)&&!android.provider.Settings.canDrawOverlays(this))Toast.makeText(this,"请在【后台】中打开悬浮窗权限",1).show();if(getSharedPreferences("updates",0).getBoolean("auto",true))UpdateService.check(this,false);RemoteStartController.onApplicationOpen(this);}
 private void selectPage(int i){NumberPad.dismiss();connectionPage.setVisibility(i==0?0:8);remotePage.setVisibility(i==1?0:8);backgroundPage.setVisibility(i==2?0:8);settingsPage.setVisibility(i==3?0:8);pageTitle.setText(new String[]{"连接","远程","后台","设置"}[i]);for(int j=0;j<tabs.size();j++){tabs.get(j).setBackground(Design.feedback(this,j==i?0xff354b5e:Design.BG,10));tabs.get(j).setTextColor(j==i?Design.ACCENT:Design.MUTED);}if(i==1&&remotePanel!=null)remotePanel.enter();}
 private void showPhone(){PhoneCompanion.refresh();if(PhoneCompanion.connected()){Toast.makeText(this,"已连接",0).show();return;}List<NetworkState.Address> list=NetworkState.list();if(list.isEmpty()){Toast.makeText(this,"未发现局域网地址，请连接 Wi-Fi 或开启热点",1).show();return;}
  android.app.Dialog dialog=new android.app.Dialog(this);dialog.requestWindowFeature(android.view.Window.FEATURE_NO_TITLE);LinearLayout body=column();body.setPadding(dp(28),dp(22),dp(28),dp(22));body.setBackground(surface(Design.CARD,24));body.setClipToOutline(true);TextView title=Design.text(this,"手机助手",26);title.setGravity(android.view.Gravity.CENTER);body.addView(title);TextView help=Design.text(this,"手机连接同一网络，扫码后输入四位连接码",18);help.setGravity(android.view.Gravity.CENTER);body.addView(help);Spinner choices=new Spinner(this);List<String> labels=new ArrayList<>();for(NetworkState.Address n:list)labels.add(n.label());choices.setAdapter(new UiAdapter(this,labels));body.addView(choices);QrView qr=new QrView(this,PhoneCompanion.url(list.get(0).ip));LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(dp(230),dp(230));qp.gravity=android.view.Gravity.CENTER_HORIZONTAL;qp.topMargin=dp(10);qp.bottomMargin=dp(10);body.addView(qr,qp);TextView info=Design.text(this,"",21);info.setGravity(android.view.Gravity.CENTER);info.setTextIsSelectable(true);body.addView(info);TextView tip=Design.text(this,"也可在手机浏览器输入网址。连接成功后本弹窗会自动关闭。",16);tip.setGravity(android.view.Gravity.CENTER);body.addView(tip);Button close=Design.button(this,"关闭",dialog::dismiss);close.setBackground(Design.feedback(this,Design.ACCENT,12));close.setTextColor(Design.BG);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(dp(230),dp(56));cp.gravity=android.view.Gravity.CENTER_HORIZONTAL;cp.topMargin=dp(16);body.addView(close,cp);dialog.setContentView(body);dialog.getWindow().setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(Color.TRANSPARENT));dialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);WindowManager.LayoutParams attr=dialog.getWindow().getAttributes();attr.dimAmount=.58f;dialog.getWindow().setAttributes(attr);dialog.show();dialog.getWindow().setLayout(Math.min(dp(780),(int)(getResources().getDisplayMetrics().widthPixels*.88)),-2);
  Runnable update=()->{if(list.isEmpty())return;int selected=Math.max(0,Math.min(list.size()-1,choices.getSelectedItemPosition()));String url=PhoneCompanion.url(list.get(selected).ip);qr.setUrl(url);info.setText(url+"\n连接码："+PhoneCompanion.pin());};choices.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,android.view.View v,int n,long id){update.run();}});update.run();dialog.setOnDismissListener(d->phoneRefresh=null);phoneRefresh=()->{if(PhoneCompanion.connected()){dialog.dismiss();Toast.makeText(this,"已连接",0).show();return;}List<NetworkState.Address> fresh=NetworkState.list();StringBuilder before=new StringBuilder(),after=new StringBuilder();for(NetworkState.Address a:list)before.append(a.label());for(NetworkState.Address a:fresh)after.append(a.label());if(!before.toString().equals(after.toString())){list.clear();list.addAll(fresh);List<String> values=new ArrayList<>();for(NetworkState.Address a:list)values.add(a.label());if(values.isEmpty())values.add("暂无局域网地址");choices.setAdapter(new UiAdapter(this,values));}if(list.isEmpty()){qr.setUrl("");info.setText("网络已断开，请连接 Wi-Fi 或开启热点");}else update.run();};}
 private void prepareBridge(){try{File secretFile=new File(getFilesDir(),"bridge-token");if(!secretFile.exists()){byte[] random=new byte[16];new SecureRandom().nextBytes(random);StringBuilder b=new StringBuilder();for(byte n:random)b.append(String.format(Locale.US,"%02x",n&255));try(FileOutputStream out=new FileOutputStream(secretFile)){out.write(b.toString().getBytes("US-ASCII"));}}
  byte[] bytes=new byte[32];try(FileInputStream in=new FileInputStream(secretFile)){int offset=0,n;while(offset<32&&(n=in.read(bytes,offset,32-offset))>0)offset+=n;if(offset!=32)throw new IOException("授权信息异常，请重新打开星匣后重试");}bridgeSecret=new String(bytes,"US-ASCII");
  RootAccess.init(this);
 }catch(Exception e){String message="无法读取授权信息："+UserMessages.explain(e);output.setText(message);setRootMessage(message);}}
 private void refresh(){String old="";if(!ips.isEmpty()&&addresses.getSelectedItemPosition()<ips.size())old=ips.get(addresses.getSelectedItemPosition());networks.clear();networks.addAll(NetworkState.list());ips.clear();List<String> labels=new ArrayList<>();int selected=0;String peer=appliedIp;NetworkState.Address best=NetworkState.maintained(networks,peer,getSharedPreferences("connection",0).getString("adbInterface",""));for(int i=0;i<networks.size();i++){NetworkState.Address a=networks.get(i);ips.add(a.ip);labels.add(a.label());if(a.ip.equals(old)||a==best)selected=i;}if(labels.isEmpty()){labels.add("暂无局域网地址，请连接 Wi-Fi 或开启热点");networkStatus.setTextColor(Design.YELLOW);networkStatus.setText("暂无局域网地址，内网穿透仍可使用");}ArrayAdapter<String> adapter=new UiAdapter(this,labels,networks.isEmpty());adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);addresses.setAdapter(adapter);addresses.setSelection(selected);}
 private void refreshNetworkIfChanged(){List<NetworkState.Address> now=NetworkState.list();StringBuilder fresh=new StringBuilder(),old=new StringBuilder();for(NetworkState.Address a:now)fresh.append(a.label());for(NetworkState.Address a:networks)old.append(a.label());if(!fresh.toString().equals(old.toString())){refresh();if(rootAvailable||server!=null)readAdb();}}
 private String adbInterface(){if(networks.isEmpty())throw new IllegalArgumentException("请刷新网络地址");return networks.get(addresses.getSelectedItemPosition()).iface;}
 private void probe(){if(probing||server!=null||endingAuthorization){Toast.makeText(this,"请先停止回传或等待检测结束",0).show();return;}probing=true;probeButton.setEnabled(false);rootToggle.setChecked(false);rootToggle.setAllowed(false);setRootMessage("正在检测 Root 授权，请留意授权提示（最长 45 秒）…");new Thread(()->{CommandRunner.Result r=RootAccess.check(this,true);if(!dead)runOnUiThread(()->{if(endingAuthorization)return;probing=false;probeButton.setEnabled(true);bridgeMode=RootAccess.bridge();setRootAvailable(RootAccess.available());setRootMessage(rootAvailable?"Root 授权可用。需要在网页执行 Root 命令时，请勾选命令回传中的 Root 选项。":"尚未获得 Root 授权，请启用独立授权；若本机条件不可用，请查看检测结果。");output.setText("退出码："+r.exit+"\n标准输出：\n"+r.stdout+"\n错误输出：\n"+r.stderr+"\n"+r.error);readAdb();});},"root-probe").start();}
 private void startServer(){syncSession();if(server!=null||probing||endingAuthorization){Toast.makeText(this,"请先停止命令回传，或等待检测完成",0).show();return;}boolean allowRoot=rootToggle.isChecked();String host=ips.isEmpty()?"":ips.get(addresses.getSelectedItemPosition());if(!networks.isEmpty())getSharedPreferences("connection",0).edit().putString("consoleInterface",adbInterface()).apply();probing=true;startButton.setEnabled(false);probeButton.setEnabled(false);rootToggle.setAllowed(false);new Thread(()->{String failure="";try{if(allowRoot)RootAccess.check(this,false);ConsoleService.startSession(this,host,allowRoot);}catch(Exception e){failure=UserMessages.explain(e);}String error=failure;if(!dead)runOnUiThread(()->{probing=false;setRootAvailable(RootAccess.available());if(error.isEmpty())syncSession();else{sessionError.setText("启动失败："+error);sessionError.setVisibility(0);startButton.setEnabled(true);probeButton.setEnabled(true);}});},"start-console").start();}
 private void stopServer(){sessionError.setVisibility(8);ConsoleService.endSession();if(!ConsoleService.active(this))stopService(new Intent(this,ConsoleService.class));server=null;sessionUrl="";token="";sessionState.setText("回传已停止；旧连接码已作废");sessionHeading.state(false);setRootMessage(RootAccess.available()?"Root 授权可用，可勾选网页 Root 命令后重新启动回传。":"尚未获得有效 Root 授权，请重新授权。");addresses.setEnabled(true);rootToggle.setChecked(false);setRootAvailable(RootAccess.available());startButton.setEnabled(!probing);probeButton.setEnabled(!probing);}
 private void setStable(TextView view,String value){if(!view.getText().toString().equals(value))view.setText(value);}
 private void syncSession(){server=ConsoleService.server;if(sessionHeading!=null)sessionHeading.state(server!=null);if(server==null){addresses.setEnabled(true);startButton.setEnabled(!probing&&!endingAuthorization);probeButton.setEnabled(!probing&&!endingAuthorization);rootToggle.setAllowed(RootAccess.available()&&!probing&&!endingAuthorization);return;}sessionUrl=ConsoleService.url;token=ConsoleService.pin;bridgeMode=RootAccess.bridge();setStable(rootState,"状态："+(!RootAccess.available()?"尚未获得有效 Root 授权，请重新授权。":ConsoleService.root?"本次连接已允许 root 命令，切到后台仍保持回传。":"本次连接使用普通权限；停止后可选择网页 Root 命令。"));setStable(sessionState,"网址："+sessionUrl+"\n连接码："+token+"\n权限："+(ConsoleService.root?"普通 + root":"仅普通应用")+"\n后台保持连接，可切到其他应用");String warning=ConsoleService.error;if(!android.provider.Settings.canDrawOverlays(this))warning=(warning.isEmpty()?"":warning+"\n")+"悬浮窗未授权，服务仍在运行";sessionError.setVisibility(warning.isEmpty()?8:0);setStable(sessionError,warning);addresses.setEnabled(false);rootToggle.setChecked(ConsoleService.root);rootToggle.setAllowed(false);startButton.setEnabled(false);probeButton.setEnabled(false);}
 private final Runnable sessionTick=new Runnable(){public void run(){if(!dead){if(server!=null&&ConsoleService.server==null){server=null;sessionUrl="";token="";sessionState.setText("连接服务已停止，请重新启动");addresses.setEnabled(true);startButton.setEnabled(true);probeButton.setEnabled(!probing);}syncSession();refreshNetworkIfChanged();PhoneCompanion.refresh();if(phoneButton!=null)setStable(phoneButton,"手机助手 · "+PhoneCompanion.status());if(phoneRefresh!=null)phoneRefresh.run();AdbMaintenance.refresh(MainActivity.this);refreshRootIndicator();renderUpdate();if(remotePanel!=null)remotePanel.refresh();sessionHandler.postDelayed(this,1000);}}};
 private String adbHost(){if(ips.isEmpty())throw new IllegalArgumentException("请连接 Wi-Fi 并刷新地址");return AdbControl.ipv4(ips.get(addresses.getSelectedItemPosition()));}
 private CommandRunner controlRunner(){return RootAccess.runner(this);}
 private void updateIpState(){if(ipState==null)return;String draft=computerIp.getText().toString().trim();ipState.setTextColor(!draft.equals(appliedIp)?Design.YELLOW:Design.MUTED);ipState.setText(!draft.equals(appliedIp)?"待应用 · 当前生效："+(appliedIp.isEmpty()?"未设置":appliedIp):appliedIp.isEmpty()?"请填写电脑 IPv4 后确认":"当前生效："+appliedIp);}
 private void applyComputerIp(){if(adbBusy)return;final String pc,host,net,previous=appliedIp;try{pc=AdbControl.ipv4(computerIp.getText().toString().trim());host=networks.isEmpty()?"":adbHost();net=networks.isEmpty()?"":adbInterface();}catch(Exception e){ipState.setTextColor(Design.YELLOW);ipState.setText(e.getMessage());Toast.makeText(this,e.getMessage(),1).show();return;}NumberPad.dismiss();adbBusy=true;applyIp.setEnabled(false);wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);ipState.setTextColor(Design.MUTED);ipState.setText("正在应用…");new Thread(()->{CommandRunner runner=controlRunner();CommandRunner.Result r=null;String failure="";boolean enabled=false;try{synchronized(AdbControl.LOCK){CommandRunner.Result state=runner.execute(AdbControl.status(host,previous,net),true,5);if(state.exit!=0||state.timedOut||!state.error.isEmpty()||!state.stdout.contains("WIFI_ENABLED="))throw new IOException("无法读取 ADB 状态，请先完成 Root 提权");AdbStatus actual=new AdbStatus(state.stdout);if(actual.listen<0||actual.lan<0)throw new IOException("ADB 状态未知，请重新检测");enabled=actual.lan==1&&actual.listen==1;if(enabled){if(host.isEmpty())throw new IOException("暂无局域网地址，无法放行电脑 IP");r=runner.execute(AdbControl.wireless(true,host,pc,net),true,10);if(r.exit!=0||r.timedOut||!r.error.isEmpty())throw new IOException(r.stderr+" "+r.error);CommandRunner.Result verify=runner.execute(AdbControl.status(host,pc,net),true,5);if(verify.exit!=0||!verify.stdout.contains("WIRELESS=true")||!verify.stdout.contains("LISTEN=true"))throw new IOException("放行规则未通过检测，请重试");}getSharedPreferences("connection",0).edit().putString("computerIp",pc).putBoolean("adbManaged",enabled).putString("adbInterface",net).putString("adbNetwork",enabled?net+"|"+host+"|"+pc:"").commit();}}catch(Exception e){failure=UserMessages.explain(e);try{if(enabled&&!previous.isEmpty())runner.execute(AdbControl.wireless(true,host,previous,net),true,10);}catch(Exception ignored){}}finally{runner.close();}final String error=failure;final boolean active=enabled;if(!dead)runOnUiThread(()->{adbBusy=false;applyIp.setEnabled(true);if(error.isEmpty()){appliedIp=pc;updateIpState();Toast.makeText(this,active?"已应用，已允许此 IP 使用无线 ADB":"已保存，开启无线 ADB 后生效",1).show();if(active)startForegroundService(new Intent(this,ConsoleService.class));}else{ipState.setTextColor(Design.YELLOW);ipState.setText("应用失败："+error);Toast.makeText(this,"应用失败："+error,1).show();}readAdb();});},"apply-computer-ip").start();}
 private void adbNotice(String message){networkStatus.setTextColor(Design.YELLOW);setStable(networkStatus,message);networkStatus.setVisibility(message.isEmpty()?8:0);}
 private void setAdbChecks(AdbStatus state){
  wirelessEnabled=state.wirelessState()==1;syncingAdb=true;wirelessToggle.setChecked(wirelessEnabled);wiredToggle.setChecked(state.wired==1);
  wirelessToggle.setText(state.wirelessLabel());wirelessToggle.setTextColor(state.wirelessWarning()?Design.YELLOW:Design.TEXT);
  wiredToggle.setText(state.wired<0?"有线ADB - 状态未知":state.wired==1?"有线ADB - 已开启":"有线ADB - 已关闭");
  ((Design.AdbAction)wirelessToggle).state(state.wirelessState());((Design.AdbAction)wiredToggle).state(state.wired);syncingAdb=false;
  wirelessToggle.setEnabled(rootAvailable&&state.wirelessState()>=0);wiredToggle.setEnabled(rootAvailable&&state.wired>=0);
  String warning=networks.isEmpty()?"暂无局域网地址，内网穿透仍可使用":state.wirelessHint();
  if(wirelessEnabled&&!networks.isEmpty()&&!appliedIp.isEmpty()&&!networks.get(addresses.getSelectedItemPosition()).contains(appliedIp))warning="本次为跨网段IP · 请确认路由或 NAT 可达"+(warning.isEmpty()?"":"\n"+warning);
  adbNotice(warning);
 }
 private void unknownAdb(String label){wirelessToggle.setText("无线ADB - "+label);wirelessToggle.setTextColor("检测中".equals(label)?Design.MUTED:Design.YELLOW);wiredToggle.setText("有线ADB - "+label);((Design.AdbAction)wirelessToggle).state(-1);((Design.AdbAction)wiredToggle).state(-1);adbNotice("检测中".equals(label)?"":"无法确认 ADB 状态，请检查 Root 授权并重新检测");}

 private void readAdb(){if(adbBusy)return;String command;try{command=networks.isEmpty()?AdbControl.status("","",""):AdbControl.status(adbHost(),appliedIp,adbInterface());}catch(Exception e){unknownAdb("状态未知");output.setText(e.getMessage());return;}adbBusy=true;applyIp.setEnabled(false);wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);unknownAdb("检测中");new Thread(()->{CommandRunner runner=controlRunner();CommandRunner.Result r;synchronized(AdbControl.LOCK){r=runner.execute(command,true,5);}runner.close();if(!dead)runOnUiThread(()->{adbBusy=false;applyIp.setEnabled(true);if(r.exit==0&&!r.timedOut&&r.error.isEmpty()&&r.stdout.contains("WIRED=")){setAdbChecks(new AdbStatus(r.stdout));output.setText("已读取车机实际设置。\n"+wirelessToggle.getText()+"\n"+wiredToggle.getText()+"\n已允许表示放行规则生效，电脑连接需另行验证。");}else{wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);unknownAdb("状态未知");output.setText("读取失败，请先完成 Root 提权：\n"+r.stderr+"\n"+r.error);}});},"adb-state").start();}
 private void changeAdb(boolean wireless,boolean on){
  if(adbBusy)return;
  syncingAdb=true;(wireless?wirelessToggle:wiredToggle).setChecked(!on);syncingAdb=false;
  final String command,host,net,peer=appliedIp;
  try{host=networks.isEmpty()?"":adbHost();net=networks.isEmpty()?"":adbInterface();if(wireless&&on&&host.isEmpty())throw new IllegalArgumentException("请连接 Wi-Fi 或开启车机热点，再开启无线 ADB");command=wireless?(on?AdbControl.wireless(true,host,peer,net):AdbControl.wireless(false,"","","")):AdbControl.wired(on);}
  catch(Exception e){adbNotice(e.getMessage());output.setText(e.getMessage());Toast.makeText(this,e.getMessage(),1).show();return;}
  adbBusy=true;applyIp.setEnabled(false);wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);output.setText("正在更新 ADB 设置…");
  new Thread(()->{
   CommandRunner runner=controlRunner();AdbStatus verified=null;String failure="";
   try{verified=AdbChange.apply(runner,command,host.isEmpty()?AdbControl.status("","",""):AdbControl.status(host,peer,net),wireless,on,()->{
    if(wireless&&!getSharedPreferences("connection",0).edit().putBoolean("adbManaged",on).putString("adbInterface",on?net:getSharedPreferences("connection",0).getString("adbInterface","")).putString("adbNetwork",on?net+"|"+host+"|"+peer:"").commit())throw new IOException("设置保存失败，请重试");
   });}catch(Exception e){failure=UserMessages.explain(e);}finally{runner.close();}
   final AdbStatus actual=verified;final String error=failure;
   if(!dead)runOnUiThread(()->{
    adbBusy=false;applyIp.setEnabled(true);
    if(!error.isEmpty()){adbNotice("修改失败："+error);output.setText("修改失败："+error);Toast.makeText(this,"修改失败："+error,1).show();readAdb();return;}
    setAdbChecks(actual);String result=(wireless?"无线ADB":"有线ADB")+(on?"已开启":"已关闭");output.setText(result+(wireless&&!on?"；内网穿透的本机通道不受影响":""));Toast.makeText(this,result,0).show();
    if(wireless){if(on)startForegroundService(new Intent(this,ConsoleService.class));else if(!ConsoleService.active(this))stopService(new Intent(this,ConsoleService.class));}
   });
  },"adb-change").start();
 }

 private void setRootMessage(String value){rootState.setText("状态："+value);}
 private void setRootAvailable(boolean value){rootAvailable=value;bridgeMode=RootAccess.bridge();if(rootState!=null)rootState.setTextColor(value?Design.GREEN:Design.RED);if(rootToggle!=null){rootToggle.setAllowed(value&&!probing&&ConsoleService.server==null&&!endingAuthorization);if(!value){rootToggle.setChecked(false);if(ConsoleService.server!=null){ConsoleService.server.disableRoot();ConsoleService.root=false;}}}}
 private void refreshRootIndicator(){RootAccess.refresh(this);boolean before=rootAvailable;setRootAvailable(RootAccess.available());if(before!=rootAvailable)setRootMessage(rootAvailable?"Root 授权可用。需要在网页执行 Root 命令时，请勾选命令回传中的 Root 选项。":"尚未获得有效 Root 授权，请重新授权。");}
 private void checkBridgeOnResume(){if(probing||server!=null||endingAuthorization){RootAccess.refresh(this);return;}probing=true;probeButton.setEnabled(false);startButton.setEnabled(false);rootToggle.setChecked(false);rootToggle.setAllowed(false);setRootMessage("正在检查 Root 提权…");new Thread(()->{CommandRunner.Result r=RootAccess.check(this,false);if(!dead)runOnUiThread(()->{if(endingAuthorization)return;probing=false;probeButton.setEnabled(true);startButton.setEnabled(true);setRootAvailable(RootAccess.available());setRootMessage(RootAccess.message());if(!rootAvailable&&RootAccess.needsConsent()&&!rootConsentShown)showRootConsent();if(rootAvailable)output.setText("自动检查成功：\n"+r.stdout);readAdb();});},"bridge-resume-probe").start();}

 private void buildBackground(){
  LinearLayout runtime=column();card(runtime);backgroundPage.addView(runtime,new LinearLayout.LayoutParams(-1,-2));runtime.addView(Design.text(this,"运行与恢复",26));
  LinearLayout options=new LinearLayout(this);runtime.addView(options);keepAliveToggle=runtimeToggle(options,"星匣后台保活");
  LinearLayout children=column();children.setPadding(dp(28),0,0,0);runtime.addView(children);
  statusBarToggle=new CheckBox(this);statusBarToggle.setText("状态栏保活（进入 Flyme 状态栏）");styleToggle(statusBarToggle);statusBarToggle.setTextSize(18);children.addView(statusBarToggle);statusBarToggle.setOnCheckedChangeListener((v,on)->saveKeepAliveChild(true,on));
  overlayToggle=new CheckBox(this);overlayToggle.setText("保活悬浮窗（点按返回主界面，长按截图到下载文件夹，按住拖动移动位置）");styleToggle(overlayToggle);overlayToggle.setTextSize(18);children.addView(overlayToggle);overlayToggle.setOnCheckedChangeListener((v,on)->saveKeepAliveChild(false,on));
  LinearLayout tools=new LinearLayout(this);children.addView(tools);overlayPermissionButton=Design.button(this,"悬浮窗权限",this::requestOverlayPermission);overlayCenterButton=Design.button(this,"恢复悬浮窗到屏幕中央",()->{startForegroundService(new Intent(this,ConsoleService.class).setAction("center"));Toast.makeText(this,"已恢复中央位置",0).show();});
  for(Button control:new Button[]{overlayPermissionButton,overlayCenterButton}){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(270),dp(48));p.setMargins(0,dp(4),dp(12),dp(4));tools.addView(control,p);}
  keepAliveChildHint=Design.text(this,"",16);children.addView(keepAliveChildHint);
  LinearLayout otherOptions=new LinearLayout(this);runtime.addView(otherOptions);autoStartToggle=runtimeToggle(otherOptions,"开机自启");autoStartToggle.setLayoutParams(new LinearLayout.LayoutParams(dp(240),dp(54)));
  runtime.addView(Design.text(this,"开机自启不限制主动退出。车机休眠或系统停止后台后，连接可能中断；可重新打开星匣恢复连接。",17));syncRuntimeOptions();
 }
 private void buildSettings(){LinearLayout saved=panel;
  LinearLayout row=new LinearLayout(this);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,0,1);settingsPage.addView(row,rp);panel=newCard(row,1);
  text("手机助手",26);CheckBox cross=new CheckBox(this);cross.setText("同步其他应用复制的内容");styleToggle(cross);cross.setChecked(getSharedPreferences("phone",0).getBoolean("crossClipboard",false));panel.addView(cross);cross.setOnCheckedChangeListener((v,on)->getSharedPreferences("phone",0).edit().putBoolean("crossClipboard",on).apply());text("仅发送给已连接的手机；默认关闭。焦点填写仅支持星匣。",18);button("解除手机连接 / 刷新连接码",()->{PhoneCompanion.unpair();Toast.makeText(this,"已解除连接，连接码已刷新",0).show();});
  panel=newCard(row,1);updateCard=panel;text("版本更新",26);text("E02星匣 · "+UpdateService.installedName(this),21);CheckBox auto=new CheckBox(this);auto.setText("打开时自动检查更新");styleToggle(auto);auto.setChecked(getSharedPreferences("updates",0).getBoolean("auto",true));panel.addView(auto);auto.setOnCheckedChangeListener((v,on)->getSharedPreferences("updates",0).edit().putBoolean("auto",on).apply());button("手动检查更新",()->{UpdateService.check(this,true);renderUpdate();});updateStatus=text(UpdateService.state().message,18);statusBox(updateStatus);
  mirrorHint=text("建议使用镜像站，点击进行网络测试",18);mirrorHint.setTextColor(Design.ACCENT);mirrorHint.setMinHeight(dp(48));mirrorHint.setGravity(android.view.Gravity.CENTER_VERTICAL);mirrorHint.setBackground(Design.feedback(this,Design.CARD,12));mirrorHint.setOnClickListener(v->startMirrorTest());mirrorHint.setVisibility(8);button("取消检查或下载",()->{if(UpdateService.busy)UpdateService.cancel();else Toast.makeText(this,"当前没有检查或下载任务",0).show();});text("点击新版提示查看简介，再下载并确认 Root 安装。安装包保存在下载文件夹，安装成功后自动删除。",17);text("初始化",26);text("清除星匣配置与设置，再次显示首次使用提示。",18);Button reset=button("初始化",()->confirmInitialization());Design.actionColor(reset,false);
  panel=newCard(row,1);text("GitHub 加速线路",26);updateRoutes=new Spinner(this);String[] names={"GitHub 直连","gh-proxy.com","gh-proxy.org","ghproxy.net","githubproxy.cc","ghfast.top","自定义 HTTPS 域名"};updateRoutes.setAdapter(new UiAdapter(this,names));panel.addView(updateRoutes);routeCustom=new EditText(this);routeCustom.setSingleLine(true);Design.input(routeCustom,"设置 → GitHub 加速域名",false);routeCustom.setHint("https://你的加速域名");panel.addView(routeCustom);NumberPad.attach(routeCustom);syncUpdateRoute();updateRoutes.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,android.view.View v,int n,long id){routeCustom.setVisibility(n==6?0:8);}});
  button("保存线路",()->{if(UpdateService.busy){Toast.makeText(this,"请等待当前任务完成",1).show();return;}try{String value=UpdatePolicy.normalize(updateRoutes.getSelectedItemPosition()==6?routeCustom.getText().toString():UpdatePolicy.ROUTES[updateRoutes.getSelectedItemPosition()]);getSharedPreferences("updates",0).edit().putString("proxy",value).apply();Toast.makeText(this,"已保存，检查与下载均使用此线路",1).show();}catch(Exception e){Toast.makeText(this,e.getMessage(),1).show();}});button("测试已保存线路",()->UpdateService.check(this,true));mirrorTestButton=button("自动测试镜像站",this::startMirrorTest);text("依次测试预设镜像站，找到可用线路后询问是否保存。",17);panel=saved;
  updateNotice=Design.text(this,"",18);updateNotice.setTextColor(Design.MUTED);updateNotice.setCompoundDrawablePadding(dp(10));android.graphics.drawable.GradientDrawable dot=new android.graphics.drawable.GradientDrawable();dot.setShape(android.graphics.drawable.GradientDrawable.OVAL);dot.setColor(Design.DANGER);dot.setBounds(0,0,dp(10),dp(10));updateNotice.setCompoundDrawables(dot,null,null,null);updateNotice.setPadding(dp(12),0,dp(12),0);updateNotice.setGravity(android.view.Gravity.CENTER_VERTICAL);updateNotice.setSingleLine(true);updateNotice.setMinHeight(dp(48));FrameLayout.LayoutParams notice=new FrameLayout.LayoutParams(-2,dp(48),android.view.Gravity.BOTTOM|android.view.Gravity.RIGHT);notice.setMargins(dp(16),dp(16),dp(30),dp(22));rootFrame.addView(updateNotice,notice);updateNotice.setVisibility(8);updateNotice.setBackground(Design.feedback(this,Design.BG,12));updateNotice.setOnClickListener(v->showUpdateDetails());}
 private void syncUpdateRoute(){String route=getSharedPreferences("updates",0).getString("proxy","");int pos=6;for(int i=0;i<UpdatePolicy.ROUTES.length;i++)if(route.equals(UpdatePolicy.ROUTES[i]))pos=i;updateRoutes.setSelection(pos);routeCustom.setText(route);routeCustom.setVisibility(pos==6?0:8);}
 private class RootOption extends CheckBox {
  private boolean allowed;
  RootOption(){super(MainActivity.this);}
  void setAllowed(boolean value){allowed=value;setTextColor(value?Design.TEXT:Design.MUTED);}
  @Override public boolean performClick(){
   String reason="";
   if(ConsoleService.server!=null)reason=ConsoleService.root?"当前回传已允许 Root 命令。若需修改，请先点击【停止回传】。":"请先点击【停止回传】，勾选此项后再启动命令回传。";
   else if(probing)reason="正在检测 Root，请等待检测结束后再勾选。";
   else if(!rootAvailable)reason="请先点击【启用独立授权】并确认。检测到 Root 授权可用后，即可勾选。";
   else if(!allowed)reason="正在更新授权状态，请稍后再勾选。";
   if(!reason.isEmpty()){Design.show(new android.app.AlertDialog.Builder(MainActivity.this).setTitle("如何启用网页 Root 命令").setMessage(reason).setPositiveButton("明白",null));return true;}
   return super.performClick();
  }
 }
 private void showRootConsent(){if(dead||endingAuthorization)return;if(rootConsentDialog!=null&&rootConsentDialog.isShowing())return;rootConsentShown=true;rootConsentDialog=RootConsent.show(this,this::enableIndependentRoot);rootConsentDialog.setOnDismissListener(dialog->rootConsentDialog=null);}
 private void enableIndependentRoot(){if(probing||endingAuthorization||RootAccess.busy()){Toast.makeText(this,"正在处理授权，请稍后重试",0).show();return;}probing=true;independentRootButton.setEnabled(false);probeButton.setEnabled(false);startButton.setEnabled(false);setRootAvailable(false);setRootMessage("正在建立星匣独立授权…");new Thread(()->{CommandRunner.Result result=RootAccess.enableIndependent(this);if(!dead)runOnUiThread(()->{probing=false;independentRootButton.setEnabled(true);probeButton.setEnabled(true);setRootAvailable(RootAccess.available());syncSession();setRootMessage(result.error.isEmpty()?RootAccess.message():result.error);output.setText(result.stdout+"\n"+result.error);if(rootAvailable)readAdb();});},"starbox-own-root").start();}
 private void confirmEndAuthorization(){RootConfirm.show(this,this::endAuthorizationNow);}
 private void endAuthorizationNow(){if(UpdateService.state().phase==UpdateService.Phase.INSTALLING){Toast.makeText(this,"正在安装，请等待完成后再结束提权",1).show();return;}UpdateService.stopForRevocation();if(endingAuthorization)return;rootConsentShown=true;endingAuthorization=true;RuntimeRecovery.cancel();RootAccess.beginRevoke();setRootAvailable(false);rootToggle.setChecked(false);new Thread(()->{CommandRunner.Result stopped=RootAccess.stop(this,true);RootAccess.finishRevoke();if(!dead)runOnUiThread(()->{endingAuthorization=false;probing=false;setRootAvailable(false);syncSession();setRootMessage(stopped.error.isEmpty()?"提权已结束，需要使用时请再次启用独立授权。":stopped.error);if(!stopped.error.isEmpty())Toast.makeText(this,stopped.error,1).show();wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);startButton.setEnabled(server==null);probeButton.setEnabled(true);});},"end-root").start();}
 private void requestOverlayPermission(){
  if(android.provider.Settings.canDrawOverlays(this)){Toast.makeText(this,"已具有悬浮窗权限，无需再次授权",1).show();return;}
  Intent[] routes={new Intent(android.provider.Settings.ACTION_MANAGE_OVERLAY_PERMISSION,android.net.Uri.parse("package:"+getPackageName())),new Intent(android.provider.Settings.ACTION_MANAGE_OVERLAY_PERMISSION),new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,android.net.Uri.parse("package:"+getPackageName()))};
  for(Intent route:routes){try{if(route.resolveActivity(getPackageManager())!=null){startActivity(route);return;}}catch(android.content.ActivityNotFoundException|SecurityException unavailable){/* Some car firmware removes or restricts Android settings activities. */}}
  Design.show(new android.app.AlertDialog.Builder(this).setTitle("车机未提供悬浮窗授权入口").setMessage("请在车机的应用管理或权限管理中，为E02星匣开启悬浮窗权限，再返回本程序。若系统没有此选项，可使用你已有的权限管理工具。\n\n未授权时，手机助手等服务仍可使用，保活悬浮窗暂不显示。").setPositiveButton("明白",null));
 }
 private void startMirrorTest(){if(UpdateService.busy){Toast.makeText(this,"请等待当前任务完成",0).show();return;}UpdateService.testMirrors(this);renderUpdate();}
 private void renderUpdate(){UpdateService.State state=UpdateService.state();if(updateStatus!=null)setStable(updateStatus,state.message);if(mirrorHint!=null)mirrorHint.setVisibility(state.phase==UpdateService.Phase.CHECK_FAILED?0:8);if(mirrorTestButton!=null){mirrorTestButton.setEnabled(!UpdateService.busy);setStable(mirrorTestButton,state.phase==UpdateService.Phase.TESTING?"正在测试镜像站…":"自动测试镜像站");}if(updateNotice!=null){String notice=state.notice();updateNotice.setVisibility(notice.isEmpty()?8:0);setStable(updateNotice,notice);}String mirror=UpdateService.takeMirror();if(!mirror.isEmpty())Design.show(new android.app.AlertDialog.Builder(this).setTitle("找到可用镜像站").setMessage(mirror.replace("https://","")+" 已通过更新清单和安装包入口测试。\n\n是否将此镜像站用于今后的更新检查和下载？").setPositiveButton("使用",(d,w)->{getSharedPreferences("updates",0).edit().putString("proxy",mirror).apply();syncUpdateRoute();UpdateService.check(this,true);}).setNegativeButton("取消",null));
  if(state.phase==UpdateService.Phase.READY&&state.release!=null){String id=state.release.sha;if(!id.equals(installPromptId)){installPromptId=id;askInstall();}}}
 private void showUpdateDetails(){UpdateService.State state=UpdateService.state();if(state.phase==UpdateService.Phase.CHECK_FAILED){selectPage(3);if(updateCard!=null)updateCard.post(()->updateCard.requestRectangleOnScreen(new android.graphics.Rect(0,0,updateCard.getWidth(),dp(310)),false));return;}if(state.ready()){askInstall();return;}if(state.release==null)return;
  if(updateDialog!=null&&updateDialog.isShowing())return;android.app.AlertDialog.Builder builder=new android.app.AlertDialog.Builder(this).setTitle("新版本 "+state.release.version).setMessage(state.release.notes+(state.message.isEmpty()?"":"\n\n"+state.message));
  if(state.phase==UpdateService.Phase.DOWNLOADING)builder.setPositiveButton("取消下载",(d,w)->UpdateService.cancel()).setNegativeButton("关闭",null);else if(state.phase==UpdateService.Phase.INSTALLING)builder.setPositiveButton("明白",null);else builder.setPositiveButton("下载",(d,w)->UpdateService.download(this)).setNegativeButton("取消",null);updateDialog=Design.show(builder);updateDialog.setOnDismissListener(d->updateDialog=null);}
 private void askInstall(){UpdateService.State state=UpdateService.state();if(!state.ready()||state.release==null)return;if(updateDialog!=null&&updateDialog.isShowing())updateDialog.dismiss();updateDialog=Design.show(new android.app.AlertDialog.Builder(this).setTitle("安装新版本 "+state.release.version+"？").setMessage("安装包已保存在下载文件夹，并通过完整性、版本、包名和原签名校验。\n\n确认后使用当前 Root 授权覆盖安装，保留现有配置。程序可能会关闭，安装成功后自动删除安装包。\n\n"+state.release.notes).setPositiveButton("安装",(d,w)->UpdateService.install(this)).setNegativeButton("取消",null));updateDialog.setOnDismissListener(d->updateDialog=null);}
 private void confirmInitialization(){
  android.app.AlertDialog d=new android.app.AlertDialog.Builder(this).setTitle("初始化 E02星匣？").setMessage("将清除星匣的所有配置、设置、连接凭证和首次使用确认记录，并停止手机助手、命令回传、内网穿透和本次 Root 提权。此操作无法撤销。\n\n初始化后程序会关闭。请重新打开 E02星匣，查看首次启动的免责声明与风险告知，并重新配置所需功能。\n\n不会恢复车机出厂设置，也不会修改当前系统 ADB 设置；下载文件夹里的截图会保留。").setNegativeButton("取消",null).setPositiveButton("确认初始化",(dialog,which)->initializeApplication()).create();
  d.setOnShowListener(v->{Design.dialog(d);Design.actionColor(d.getButton(android.app.AlertDialog.BUTTON_POSITIVE),false);});d.show();
 }
 private void initializeApplication(){
  if(UpdateService.state().phase==UpdateService.Phase.INSTALLING){Toast.makeText(this,"正在安装，请等待完成后再初始化",1).show();return;}if(dead)return;RuntimeRecovery.cancel();RootAccess.beginRevoke();dead=true;sessionHandler.removeCallbacksAndMessages(null);NumberPad.dismiss();PhoneCompanion.stop();UpdateService.cancel();RemoteService.stop(this);stopService(new Intent(this,UpdateService.class));
  new Thread(()->{try{
   ConsoleService.endSession();String secret=exitBridgeToken();CommandRunner.Result stopped=RootAccess.stop(this,true);if(!stopped.error.isEmpty())throw new IOException(stopped.error);if(!StatusBarEntry.disableForExit(this))throw new IOException(StatusBarEntry.error);
   if(!secret.isEmpty()){CommandRunner.Result check=new BridgeRunner(secret,false).execute("id",true,2);if(check.exit==0&&!check.timedOut&&check.stdout.matches("(?s).*\\buid=0\\(root\\).*"))throw new IOException("Root 提权尚未停止，请稍后重试");}
   stopService(new Intent(this,ConsoleService.class));
   android.app.ActivityManager manager=(android.app.ActivityManager)getSystemService(ACTIVITY_SERVICE);
   if(manager==null||!manager.clearApplicationUserData())throw new IOException("系统未允许初始化，请在车机应用管理中清除星匣的数据");
  }catch(Exception e){runOnUiThread(()->{RootAccess.finishRevoke();dead=false;Toast.makeText(this,"初始化未完成："+UserMessages.explain(e),Toast.LENGTH_LONG).show();recreate();});}},"starbox-initialize").start();
 }
 private String exitBridgeToken(){if(!bridgeSecret.isEmpty())return bridgeSecret;try{byte[] bytes=new byte[32];try(DataInputStream in=new DataInputStream(new FileInputStream(new File(getFilesDir(),"bridge-token")))){in.readFully(bytes);if(in.read()!=-1)return "";}String secret=new String(bytes,"US-ASCII");return secret.matches("[0-9a-f]{32}")?secret:"";}catch(IOException ignored){return "";}}
 private CheckBox runtimeToggle(LinearLayout row,String name){CheckBox option=new CheckBox(this);option.setText(name);styleToggle(option);option.setTextSize(18);row.addView(option,new LinearLayout.LayoutParams(0,dp(54),1));option.setOnCheckedChangeListener((view,on)->saveRuntimeOptions());return option;}
 private void syncRuntimeOptions(){RuntimePolicy.Snapshot state=RuntimeSettings.snapshot(this);boolean healthy=RuntimeSettings.healthy(this);syncingRuntime=true;for(CheckBox option:new CheckBox[]{keepAliveToggle,autoStartToggle})if(option!=null)option.setEnabled(healthy);if(keepAliveToggle!=null)keepAliveToggle.setChecked(state.keepAlive);if(autoStartToggle!=null)autoStartToggle.setChecked(state.autoStart);syncingRuntime=false;if(quitButton!=null)ExitConfirm.style(quitButton,!healthy||ExitPolicy.blocked(state.keepAlive,state.autoStart,state.parkedRemote,RuntimeSettings.wakeRecovery(this)));syncKeepAliveChildren();}
 private void saveRuntimeOptions(){if(syncingRuntime||keepAliveToggle==null||autoStartToggle==null)return;boolean saved=RuntimeSettings.configure(this,keepAliveToggle.isChecked(),autoStartToggle.isChecked(),RuntimeSettings.snapshot(this).parkedRemote);syncRuntimeOptions();if(!saved)Toast.makeText(this,"设置未保存，请检查星匣的存储空间后重试",1).show();else{StatusBarEntry.sync(this);syncKeepAliveChildren();RuntimeRecovery.cancel();startForegroundService(new Intent(this,ConsoleService.class).setAction("options"));}}
 private void syncKeepAliveChildren(){
  if(statusBarToggle==null||overlayToggle==null)return;syncingChildren=true;boolean enabled=RuntimeSettings.healthy(this)&&RuntimeSettings.snapshot(this).keepAlive;
  statusBarToggle.setChecked(StatusBarEntry.selected(this));overlayToggle.setChecked(getSharedPreferences("connection",0).getBoolean("overlay",true));statusBarToggle.setEnabled(enabled);overlayToggle.setEnabled(enabled);overlayPermissionButton.setEnabled(enabled&&overlayToggle.isChecked());overlayCenterButton.setEnabled(enabled&&overlayToggle.isChecked());
  keepAliveChildHint.setText(!enabled?"开启星匣后台保活后可使用这两个子项目，原有选择会保留。":!StatusBarEntry.error.isEmpty()?StatusBarEntry.error:"悬浮窗贴近边缘、拖不动时，可恢复到屏幕中央。状态栏入口由系统加载，不阻止车机休眠。");syncingChildren=false;
 }
 private void saveKeepAliveChild(boolean statusBar,boolean on){
  if(syncingChildren)return;boolean saved;if(statusBar)saved=StatusBarEntry.select(this,on);else{SharedPreferences prefs=getSharedPreferences("connection",0);boolean before=prefs.getBoolean("overlay",true);saved=prefs.edit().putBoolean("overlay",on).commit();if(!saved)prefs.edit().putBoolean("overlay",before).commit();}syncKeepAliveChildren();
  if(!saved){Toast.makeText(this,statusBar?StatusBarEntry.error:"悬浮窗设置未保存，请重试",1).show();return;}
  startForegroundService(new Intent(this,ConsoleService.class).setAction("options"));if(!statusBar&&on&&!android.provider.Settings.canDrawOverlays(this))requestOverlayPermission();
 }
 private void showExitRestriction(){RuntimePolicy.Snapshot state=RuntimeSettings.snapshot(this);if(exitDialog!=null&&exitDialog.isShowing())return;exitDialog=ExitConfirm.show(this,state.keepAlive,state.autoStart,state.parkedRemote,RuntimeSettings.wakeRecovery(this),()->selectPage(2));exitDialog.setOnDismissListener(dialog->exitDialog=null);}
 private void requestExit(){if(dead)return;syncRuntimeOptions();if(!RuntimeSettings.healthy(this)){Design.show(new android.app.AlertDialog.Builder(this).setTitle("暂时无法退出").setMessage("无法读取保活设置，请重新打开星匣后重试。").setPositiveButton("明白",null));return;}RuntimePolicy.Snapshot state=RuntimeSettings.snapshot(this);if(ExitPolicy.blocked(state.keepAlive,state.autoStart,state.parkedRemote,RuntimeSettings.wakeRecovery(this))){showExitRestriction();return;}if(UpdateService.state().phase==UpdateService.Phase.INSTALLING){Toast.makeText(this,"正在安装，请等待完成后再退出",1).show();return;}RuntimePolicy.Decision decision=RuntimeSettings.requestExit(this);if(decision.has(RuntimePolicy.Effect.EXIT_BLOCKED)){syncRuntimeOptions();showExitRestriction();return;}if(decision.has(RuntimePolicy.Effect.SAVE_ERROR))Toast.makeText(this,"运行设置保存失败，程序将关闭；下次打开后请检查设置",1).show();exitApplication();}
 private void exitAfterDecliningRisk(){if(RiskNotice.accepted(this))return;exitApplication();}
 private void exitApplication(){if(dead)return;if(RiskNotice.accepted(this)){RuntimePolicy.Snapshot state=RuntimeSettings.snapshot(this);if(ExitPolicy.blocked(state.keepAlive,state.autoStart,state.parkedRemote,RuntimeSettings.wakeRecovery(this))){syncRuntimeOptions();showExitRestriction();return;}}if(UpdateService.state().phase==UpdateService.Phase.INSTALLING){Toast.makeText(this,"正在安装，请等待完成后再退出",1).show();return;}RuntimeRecovery.cancel();RootAccess.beginRevoke();dead=true;sessionHandler.removeCallbacksAndMessages(null);PhoneCompanion.stop();getSharedPreferences("connection",0).edit().putBoolean("appActive",false).putBoolean("adbManaged",false).apply();UpdateService.cancel();RemoteService.stop(this);stopService(new Intent(this,UpdateService.class));new Thread(()->{ConsoleService.endSession();CommandRunner.Result stopped=RootAccess.stop(this,false);if(!StatusBarEntry.disableForExit(this)&&stopped.error.isEmpty())stopped.error=StatusBarEntry.error;stopService(new Intent(this,ConsoleService.class));if(!stopped.error.isEmpty()){RootAccess.finishRevoke();runOnUiThread(()->{dead=false;setRootAvailable(false);setRootMessage(stopped.error);Toast.makeText(this,"退出未完成："+stopped.error,1).show();});return;}runOnUiThread(()->{finishAndRemoveTask();new android.os.Handler(android.os.Looper.getMainLooper()).postDelayed(()->android.os.Process.killProcess(android.os.Process.myPid()),400);});},"starbox-exit").start();}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==RemotePanel.IMPORT&&result==RESULT_OK&&data!=null&&data.getData()!=null)remotePanel.importUri(data.getData());}
 @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);if(!RiskNotice.accepted(this)||dead)return;if(getSharedPreferences("updates",0).getBoolean("auto",true))UpdateService.check(this,false);}
 @Override protected void onResume(){super.onResume();visible=true;syncRuntimeOptions();if(!RiskNotice.accepted(this)||dead)return;PhoneCompanion.attach(this);refreshNetworkIfChanged();syncSession();checkBridgeOnResume();if(server!=null)readAdb();sessionHandler.removeCallbacks(sessionTick);sessionHandler.post(sessionTick);}
 @Override public void onBackPressed(){if(!NumberPad.dismiss())super.onBackPressed();}
 @Override protected void onStop(){NumberPad.dismiss();PhoneCompanion.detach(this);sessionHandler.removeCallbacks(sessionTick);super.onStop();}
 @Override protected void onPause(){visible=false;super.onPause();}
 @Override protected void onDestroy(){if(rootConsentDialog!=null){rootConsentDialog.dismiss();rootConsentDialog=null;}if(exitDialog!=null){exitDialog.dismiss();exitDialog=null;}if(updateDialog!=null){updateDialog.dismiss();updateDialog=null;}if(riskDialog!=null){riskDialog.dismiss();riskDialog=null;}PhoneCompanion.detach(this);dead=true;sessionHandler.removeCallbacks(sessionTick);if(probeRunner!=null)probeRunner.close();super.onDestroy();}
}
