package com.e02.rootconsole;

import android.app.Activity;
import android.os.Bundle;
import android.graphics.Color;
import android.view.WindowManager;
import android.widget.*;
import android.content.*;
import java.io.*;
import java.net.*;
import java.security.SecureRandom;
import java.util.*;

public class MainActivity extends Activity {
 private LinearLayout panel,leftPanel;private TextView rootState,sessionState,output;private Spinner addresses;private CheckBox rootToggle;
 private android.os.Handler sessionHandler=new android.os.Handler();private Switch overlayToggle,wirelessToggle,wiredToggle;private EditText computerIp;private boolean syncingAdb,adbBusy;
 private Button probeButton,startButton;private Spinner rootHours,rootMinutes;private CheckBox permanentRoot;private ConsoleServer server;private CommandRunner probeRunner;
 private String sessionUrl="",token="",bridgeSecret="";private boolean probing,dead,bridgeMode;private final List<String> ips=new ArrayList<>();
 private int dp(int n){return (int)(getResources().getDisplayMetrics().density*n);}
 private android.graphics.drawable.GradientDrawable surface(int color,int radius){android.graphics.drawable.GradientDrawable d=new android.graphics.drawable.GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private TextView text(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(Math.max(14,size-3));v.setTextColor(Color.rgb(67,83,103));if(size>=23){v.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);v.setTextColor(Color.rgb(26,43,61));}v.setPadding(0,dp(6),0,dp(6));panel.addView(v);return v;}
 private Button button(String s,Runnable action){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextSize(15);b.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);boolean primary=s.startsWith("启动"),danger=s.startsWith("停止");b.setTextColor(primary?Color.WHITE:danger?Color.rgb(163,53,67):Color.rgb(38,76,87));b.setBackground(surface(primary?Color.rgb(24,126,111):danger?Color.rgb(253,238,239):Color.rgb(235,242,247),10));b.setMinimumHeight(0);b.setMinHeight(0);b.setElevation(primary?dp(2):0);LinearLayout.LayoutParams params=new LinearLayout.LayoutParams(-1,dp(44));params.topMargin=dp(5);params.bottomMargin=dp(6);panel.addView(b,params);b.setOnClickListener(v->action.run());return b;}
 private void card(LinearLayout view){view.setPadding(dp(18),dp(12),dp(18),dp(12));view.setBackground(surface(Color.WHITE,16));view.setElevation(dp(2));}
 private void statusBox(TextView view){view.setBackground(surface(Color.rgb(238,246,245),10));view.setPadding(dp(12),dp(9),dp(12),dp(9));view.setTextColor(Color.rgb(30,105,94));}
 private void styleToggle(CompoundButton view){view.setTextColor(Color.rgb(46,65,83));android.content.res.ColorStateList tint=new android.content.res.ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{Color.rgb(24,126,111),Color.rgb(167,179,189)});view.setButtonTintList(tint);if(view instanceof Switch){((Switch)view).setThumbTintList(tint);((Switch)view).setTrackTintList(new android.content.res.ColorStateList(new int[][]{new int[]{android.R.attr.state_checked},new int[]{}},new int[]{Color.rgb(163,213,205),Color.rgb(223,229,234)}));}}
 @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout frame=new LinearLayout(this);frame.setOrientation(1);frame.setPadding(dp(20),dp(12),dp(20),dp(14));frame.setBackgroundColor(Color.rgb(238,242,247));setContentView(frame);TextView heading=new TextView(this);heading.setText("E02 AI 连接助手");heading.setTextSize(26);heading.setTypeface(android.graphics.Typeface.DEFAULT_BOLD);heading.setTextColor(Color.rgb(23,40,33));frame.addView(heading);TextView subtitle=new TextView(this);subtitle.setText("连接 · 诊断 · 截图     /     同一 Wi-Fi，停车后使用");subtitle.setTextSize(14);subtitle.setTextColor(Color.rgb(101,119,137));subtitle.setPadding(0,dp(3),0,dp(10));frame.addView(subtitle);LinearLayout columns=new LinearLayout(this);frame.addView(columns,new LinearLayout.LayoutParams(-1,0,1));ScrollView leftScroll=new ScrollView(this),rightScroll=new ScrollView(this);columns.addView(leftScroll,new LinearLayout.LayoutParams(0,-1,1));LinearLayout.LayoutParams rightParams=new LinearLayout.LayoutParams(0,-1,1.15f);rightParams.leftMargin=dp(20);columns.addView(rightScroll,rightParams);leftPanel=new LinearLayout(this);leftPanel.setOrientation(1);card(leftPanel);leftScroll.setClipToPadding(false);leftScroll.addView(leftPanel);LinearLayout rightPanel=new LinearLayout(this);rightPanel.setOrientation(1);card(rightPanel);rightScroll.setClipToPadding(false);rightScroll.addView(rightPanel);panel=leftPanel;
  text("01   权限与有效时间",24);
  rootState=text("正在检查权限，普通连接无需 root。",19);statusBox(rootState);
  probeButton=button("重新检测 root（EVCC 桥接 / su）",()->probe());
  text("Root 桥接有效时间（从 EVCC 启动成功时开始）",18);
  LinearLayout durationRow=new LinearLayout(this);panel.addView(durationRow);rootHours=new Spinner(this);rootMinutes=new Spinner(this);durationRow.addView(rootHours,new LinearLayout.LayoutParams(0,-2,1));durationRow.addView(rootMinutes,new LinearLayout.LayoutParams(0,-2,1));List<String> hours=new ArrayList<>(),minutes=new ArrayList<>();for(int i=0;i<=24;i++)hours.add(i+" 小时");for(int i=0;i<60;i++)minutes.add(i+" 分钟");ArrayAdapter<String> hourAdapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,hours),minuteAdapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,minutes);hourAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);minuteAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);rootHours.setAdapter(hourAdapter);rootMinutes.setAdapter(minuteAdapter);android.content.SharedPreferences durationPrefs=getPreferences(MODE_PRIVATE);rootHours.setSelection(Math.max(0,Math.min(24,durationPrefs.getInt("rootHours",0))));rootMinutes.setSelection(Math.max(0,Math.min(59,durationPrefs.getInt("rootMinutes",10))));
  permanentRoot=new CheckBox(this);permanentRoot.setText("永久有效（不自动到期；手动停止或重启结束）");permanentRoot.setTextSize(16);panel.addView(permanentRoot);styleToggle(permanentRoot);permanentRoot.setOnCheckedChangeListener((v,checked)->{rootHours.setEnabled(!checked);rootMinutes.setEnabled(!checked);});permanentRoot.setChecked(durationPrefs.getBoolean("permanentRoot",false));
  button("复制桥接命令，去 EVCC 粘贴执行",()->prepareBridge(true));
  rootToggle=new CheckBox(this);rootToggle.setText("允许本次网页会话执行 root 命令");rootToggle.setTextSize(16);rootToggle.setEnabled(false);panel.addView(rootToggle);styleToggle(rootToggle);
  panel=rightPanel;text("02   连接与快捷工具",24);
  overlayToggle=new Switch(this);overlayToggle.setText("显示 E02 AI 悬浮保活窗口");overlayToggle.setTextSize(16);overlayToggle.setChecked(getSharedPreferences("connection",0).getBoolean("overlay",true));panel.addView(overlayToggle);styleToggle(overlayToggle);overlayToggle.setOnCheckedChangeListener((v,on)->{getSharedPreferences("connection",0).edit().putBoolean("overlay",on).apply();if(on&&!android.provider.Settings.canDrawOverlays(this))startActivity(new Intent(android.provider.Settings.ACTION_MANAGE_OVERLAY_PERMISSION,android.net.Uri.parse("package:"+getPackageName())));});
  text("ADB 连接设置",21);text("需要已启动的 root 桥接，进入时自动读取配置",17);
  computerIp=new EditText(this);computerIp.setSingleLine(true);computerIp.setTextSize(16);computerIp.setTextColor(Color.rgb(29,56,72));computerIp.setBackground(surface(Color.rgb(245,248,251),8));computerIp.setPadding(dp(10),dp(7),dp(10),dp(7));computerIp.setHint("允许无线 ADB 的电脑 IPv4 地址");computerIp.setText(getSharedPreferences("connection",0).getString("computerIp",""));panel.addView(computerIp);
  wirelessToggle=new Switch(this);wirelessToggle.setText("无线 ADB · 正在读取状态");wirelessToggle.setEnabled(false);wirelessToggle.setTextSize(16);panel.addView(wirelessToggle);styleToggle(wirelessToggle);
  wiredToggle=new Switch(this);wiredToggle.setText("有线 ADB · 正在读取状态");wiredToggle.setEnabled(false);wiredToggle.setTextSize(16);panel.addView(wiredToggle);styleToggle(wiredToggle);
  wirelessToggle.setOnCheckedChangeListener((v,on)->{if(!syncingAdb)changeAdb(true,on);});wiredToggle.setOnCheckedChangeListener((v,on)->{if(!syncingAdb)changeAdb(false,on);});
  button("读取 ADB 开关实际状态",()->readAdb());
  text("无线开关只调整 Wi-Fi 上的 TCP 5555 放行；关闭无线不会停止有线 ADB。电脑 IP 变化时重新填写并开启。有线切换后可能需要拔插 USB。",17);
  text("选择车机 Wi-Fi IPv4 地址",18);addresses=new Spinner(this);panel.addView(addresses);button("刷新地址",()->refresh());
  startButton=button("启动局域网命令回传",()->startServer());button("停止回传及 root 桥接，作废连接码",()->{stopServer();BridgeRunner.stop(bridgeSecret);bridgeMode=false;rootState.setText("RootService 桥接已请求停止，需要在 EVCC 重新启动后才能使用。");});
  sessionState=text("连接尚未启动",20);statusBox(sessionState);sessionState.setTextIsSelectable(true);
  button("复制网址和连接码",()->{if(sessionUrl.isEmpty()){Toast.makeText(this,"请先启动回传",0).show();return;}((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("E02 session",sessionUrl+"\n连接码："+token));Toast.makeText(this,"已复制",0).show();});
  output=text("运行结果会显示在这里",17);output.setBackground(surface(Color.rgb(245,248,251),10));output.setPadding(dp(12),dp(9),dp(12),dp(9));output.setTextIsSelectable(true);
  panel=leftPanel;
  text("使用步骤",23);text("1. 选择 root 有效时间，复制命令。\n2. 到 EVCC 粘贴，点 ROOT 运行。\n3. 返回助手，等待自动检测成功。\n4. 勾选本次 root 权限，启动连接。",17);
  text("点击悬浮文字窗截图到下载文件夹，截图会隐藏悬浮窗。长按打开助手，拖动调整位置。切到其他应用仍保持回传；点停止会作废连接码并关闭桥接。\n永久有效不按时间到期，手动停止或车机重启仍会结束。改时长后，需要重新复制命令到 EVCC 运行。",17);
  text("电脑打开右侧网址，输入本次 4 位连接码即可执行命令并查看结果。仅在可信 Wi-Fi 使用。",17);prepareBridge(false);refresh();
 }
 private static String shQuote(String s){return "'"+s.replace("'","'\\''")+"'";}
 private void prepareBridge(boolean display){try{long duration=permanentRoot.isChecked()?0:rootHours.getSelectedItemPosition()*3600L+rootMinutes.getSelectedItemPosition()*60L;if(!permanentRoot.isChecked()&&duration==0){if(display)Toast.makeText(this,"请选择至少 1 分钟，或勾选永久有效",1).show();return;}getPreferences(MODE_PRIVATE).edit().putInt("rootHours",rootHours.getSelectedItemPosition()).putInt("rootMinutes",rootMinutes.getSelectedItemPosition()).putBoolean("permanentRoot",permanentRoot.isChecked()).apply();File secretFile=new File(getFilesDir(),"bridge-token");if(!secretFile.exists()){byte[] random=new byte[16];new SecureRandom().nextBytes(random);StringBuilder b=new StringBuilder();for(byte n:random)b.append(String.format(Locale.US,"%02x",n&255));try(FileOutputStream out=new FileOutputStream(secretFile)){out.write(b.toString().getBytes("US-ASCII"));}}
  byte[] bytes=new byte[32];try(FileInputStream in=new FileInputStream(secretFile)){int offset=0,n;while(offset<32&&(n=in.read(bytes,offset,32-offset))>0)offset+=n;if(offset!=32)throw new IOException("桥接密钥长度异常");}bridgeSecret=new String(bytes,"US-ASCII");
  String command="CLASSPATH="+shQuote(getApplicationInfo().sourceDir)+" app_process /system/bin com.e02.rootconsole.RootBridge "+shQuote(secretFile.getAbsolutePath())+" "+duration+" > "+shQuote(new File(getFilesDir(),"bridge.log").getAbsolutePath())+" 2>&1 < /dev/null &";
  File script=new File(getFilesDir(),"rootbridge-start.sh");try(FileOutputStream out=new FileOutputStream(script)){out.write((command+"\n").getBytes("UTF-8"));}
  if(display){String launch="sh "+shQuote(script.getAbsolutePath());output.setText("命令已复制。切到 EVCC，在命令框粘贴后点 ROOT 执行，再返回助手。返回时会自动检查桥接。\n有效时间："+(duration==0?"永久（手动停止或重启结束）":rootHours.getSelectedItemPosition()+" 小时 "+rootMinutes.getSelectedItemPosition()+" 分钟")+"\n\n"+launch+"\n\n配合电脑时：电脑输入到焦点，你只需点 ROOT 执行、复制日志，再回复 1。\n\n不修改系统权限或 USB / 防火墙设置。");((ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("EVCC RootService bridge",launch));Toast.makeText(this,"已复制，请到 EVCC 粘贴并点 ROOT 执行",1).show();}
 }catch(Exception e){output.setText("准备桥接失败："+e.getMessage());}}
 private void refresh(){if(server!=null){Toast.makeText(this,"先停止当前会话再刷新",0).show();return;}ips.clear();List<String> labels=new ArrayList<>();try{List<NetworkInterface> nets=Collections.list(NetworkInterface.getNetworkInterfaces());Collections.sort(nets,(a,b)->Boolean.compare(!a.getName().startsWith("wlan"),!b.getName().startsWith("wlan")));for(NetworkInterface n:nets){if(!n.isUp()||n.isLoopback())continue;for(InetAddress a:Collections.list(n.getInetAddresses()))if(a instanceof Inet4Address&&!a.isLoopbackAddress()&&!a.isLinkLocalAddress()){ips.add(a.getHostAddress());labels.add(n.getName()+" · "+a.getHostAddress());}}}catch(Exception e){output.setText(e.toString());}if(labels.isEmpty())labels.add("请先连接 Wi-Fi");ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,labels);adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);addresses.setAdapter(adapter);}
 private void probe(){if(probing||server!=null){Toast.makeText(this,"请先停止回传或等待检测结束",0).show();return;}probing=true;probeButton.setEnabled(false);rootToggle.setChecked(false);rootToggle.setEnabled(false);rootState.setText("正在检测 RootService 桥接 / su，请留意授权弹窗（最长 45 秒）…");new Thread(()->{CommandRunner.Result first=new BridgeRunner(bridgeSecret,false).execute("id",true,2);boolean bridge=first.exit==0&&!first.timedOut&&first.stdout.matches("(?s).*\\buid=0\\(root\\).*");bridgeMode=bridge;
  if(!bridge){probeRunner=new CommandRunner("/system/bin/sh","su");first=probeRunner.execute("id",true,45);probeRunner.close();}final CommandRunner.Result r=first;boolean root=r.exit==0&&!r.timedOut&&r.stdout.matches("(?s).*\\buid=0\\(root\\).*");if(!dead)runOnUiThread(()->{probing=false;probeButton.setEnabled(true);rootToggle.setEnabled(root);rootState.setText(root?(bridge?"Root 可用：RootService 桥接已验证。":"Root 可用：su 授权已验证。")+"勾选后才允许网页使用 root。":"Root 不可用。请复制桥接命令到 EVCC，点 ROOT 执行后返回助手。");output.setText("退出码："+r.exit+"\n标准输出：\n"+r.stdout+"\n错误输出：\n"+r.stderr+"\n"+r.error);if(root)readAdb();});},"root-probe").start();}
 private void startServer(){syncSession();if(server!=null||probing){Toast.makeText(this,"请先停止已有会话或等待检测",0).show();return;}if(ips.isEmpty())return;String host=ips.get(addresses.getSelectedItemPosition());String newToken=String.format(Locale.US,"%04d",new SecureRandom().nextInt(10000));try{ByteArrayOutputStream page=new ByteArrayOutputStream();try(InputStream in=getAssets().open("console.html")){byte[] buffer=new byte[4096];int n;while((n=in.read(buffer))!=-1)page.write(buffer,0,n);}server=new ConsoleServer(host,38765,newToken,page.toByteArray(),rootToggle.isChecked(),bridgeMode?new BridgeRunner(bridgeSecret,true):new CommandRunner("/system/bin/sh","su"));ConsoleService.server=server;ConsoleService.pin=newToken;ConsoleService.url="http://"+host+":"+server.port()+"/";ConsoleService.root=rootToggle.isChecked();ConsoleService.bridge=bridgeMode;ConsoleService.error="";server.start();startForegroundService(new Intent(this,ConsoleService.class));syncSession();}catch(Exception e){ConsoleService.endSession();server=null;sessionState.setText("启动失败："+e.getMessage());}}
 private void stopServer(){ConsoleService.endSession();stopService(new Intent(this,ConsoleService.class));server=null;sessionUrl="";token="";sessionState.setText("回传已停止；旧连接码已作废");addresses.setEnabled(true);rootToggle.setChecked(false);rootToggle.setEnabled(false);startButton.setEnabled(true);probeButton.setEnabled(!probing);}
 private void setStable(TextView view,String value){if(!view.getText().toString().equals(value))view.setText(value);}
 private void syncSession(){server=ConsoleService.server;if(server==null)return;sessionUrl=ConsoleService.url;token=ConsoleService.pin;bridgeMode=ConsoleService.bridge;setStable(rootState,ConsoleService.root?"本次连接已允许 root 命令，切到后台仍保持回传。":"本次连接使用普通权限；停止后可重新检测 root。");setStable(sessionState,"网址："+sessionUrl+"\n连接码："+token+"\n权限："+(ConsoleService.root?"普通 + root":"仅普通应用")+"\n前台服务维持连接，可切到其他应用"+(android.provider.Settings.canDrawOverlays(this)?"":"\n悬浮窗未授权，服务仍在运行"));addresses.setEnabled(false);rootToggle.setChecked(ConsoleService.root);rootToggle.setEnabled(false);startButton.setEnabled(false);probeButton.setEnabled(false);}
 private final Runnable sessionTick=new Runnable(){public void run(){if(!dead){if(server!=null&&ConsoleService.server==null){server=null;sessionUrl="";token="";sessionState.setText("连接服务已停止，请重新启动");addresses.setEnabled(true);startButton.setEnabled(true);probeButton.setEnabled(!probing);}syncSession();sessionHandler.postDelayed(this,1000);}}};
 private String adbHost(){if(ips.isEmpty())throw new IllegalArgumentException("请连接 Wi-Fi 并刷新地址");return AdbControl.ipv4(ips.get(addresses.getSelectedItemPosition()));}
 private CommandRunner controlRunner(){return bridgeMode?new BridgeRunner(bridgeSecret,false):new CommandRunner("/system/bin/sh","su");}
 private void setAdbChecks(boolean wireless,boolean wired){syncingAdb=true;wirelessToggle.setChecked(wireless);wiredToggle.setChecked(wired);wirelessToggle.setText("无线 ADB · 允许上述电脑（5555）");wiredToggle.setText("有线 ADB · 厂家 USB 模式");syncingAdb=false;}
 private void readAdb(){if(adbBusy)return;String command;try{command=AdbControl.status(adbHost(),computerIp.getText().toString().trim());}catch(Exception e){output.setText(e.getMessage());return;}adbBusy=true;wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);new Thread(()->{CommandRunner runner=controlRunner();CommandRunner.Result r=runner.execute(command,true,5);runner.close();if(!dead)runOnUiThread(()->{adbBusy=false;wirelessToggle.setEnabled(true);wiredToggle.setEnabled(true);if(r.exit==0&&!r.timedOut&&r.stdout.contains("WIRED=")){setAdbChecks(r.stdout.contains("WIRELESS=true"),r.stdout.contains("WIRED=true"));if(r.stdout.contains("WIRELESS=unknown"))wirelessToggle.setText("无线 ADB · 请先填写电脑 IP 后读取状态");output.setText("已读取车机实际设置。\n无线 ADB："+(r.stdout.contains("WIRELESS=unknown")?"待填写电脑 IP":r.stdout.contains("WIRELESS=true")?"已允许上述电脑连接":"已关闭或未对上述电脑放行")+"\n有线 ADB："+(r.stdout.contains("WIRED=true")?"已切到 ADB 模式":"普通 USB 模式"));}else {wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);wirelessToggle.setText("无线 ADB · 状态未知");wiredToggle.setText("有线 ADB · 状态未知");output.setText("读取失败，请先通过 EVCC 启动 root 桥接：\n"+r.stderr+"\n"+r.error);}});},"adb-state").start();}
 private void changeAdb(boolean wireless,boolean on){if(adbBusy)return;String command;try{String pc=computerIp.getText().toString().trim();command=wireless?AdbControl.wireless(on,adbHost(),pc):AdbControl.wired(on);if(wireless)getSharedPreferences("connection",0).edit().putString("computerIp",pc).apply();}catch(Exception e){syncingAdb=true;(wireless?wirelessToggle:wiredToggle).setChecked(!on);syncingAdb=false;output.setText(e.getMessage());return;}adbBusy=true;wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);output.setText("正在更新 ADB 设置…");new Thread(()->{CommandRunner runner=controlRunner();CommandRunner.Result r=runner.execute(command,true,10);runner.close();if(!dead)runOnUiThread(()->{adbBusy=false;wirelessToggle.setEnabled(true);wiredToggle.setEnabled(true);if(r.exit!=0||r.timedOut||!r.error.isEmpty()){syncingAdb=true;(wireless?wirelessToggle:wiredToggle).setChecked(!on);syncingAdb=false;output.setText("修改失败：\n"+r.stdout+"\n"+r.stderr+"\n"+r.error);}else output.setText("设置已执行：\n"+r.stdout+(wireless?(on?"电脑使用 adb connect "+adbHost()+":5555":"Wi-Fi 的 5555 连接已关闭，有线仍可使用"):(on?"已切到有线 ADB，必要时拔插 USB":"已恢复普通 USB 模式")));});},"adb-change").start();}
 private void checkBridgeOnResume(){if(probing||server!=null)return;probing=true;probeButton.setEnabled(false);startButton.setEnabled(false);rootToggle.setChecked(false);rootToggle.setEnabled(false);rootState.setText("正在自动检查 RootService 桥接…");new Thread(()->{CommandRunner.Result r=new BridgeRunner(bridgeSecret,false).execute("id",true,2);boolean ok=r.exit==0&&!r.timedOut&&r.stdout.matches("(?s).*\\buid=0\\(root\\).*");if(!dead)runOnUiThread(()->{probing=false;bridgeMode=ok;probeButton.setEnabled(true);startButton.setEnabled(true);rootToggle.setEnabled(ok);rootState.setText(ok?"Root 可用：RootService 桥接已验证。勾选本次 root 权限即可启动回传。":"尚未连接 RootService 桥接。请复制命令到 EVCC 执行，或点击重新检测尝试 su。");if(ok){output.setText("自动检查成功：\n"+r.stdout);readAdb();}else{wirelessToggle.setText("无线 ADB · 状态未知，需要 root");wiredToggle.setText("有线 ADB · 状态未知，需要 root");wirelessToggle.setEnabled(false);wiredToggle.setEnabled(false);}});},"bridge-resume-probe").start();}
 @Override protected void onResume(){super.onResume();syncSession();checkBridgeOnResume();if(server!=null)readAdb();sessionHandler.removeCallbacks(sessionTick);sessionHandler.post(sessionTick);}
 @Override protected void onStop(){sessionHandler.removeCallbacks(sessionTick);super.onStop();}
 @Override protected void onDestroy(){dead=true;sessionHandler.removeCallbacks(sessionTick);if(probeRunner!=null)probeRunner.close();super.onDestroy();}
}
