package com.e02.rootconsole;
import android.app.*;
import android.content.*;
import android.net.Uri;
import android.widget.*;
import java.io.*;
import java.security.SecureRandom;


/** Overview stays compact; configuration and logs have their own views. */
public class RemotePanel extends LinearLayout {
 public static final int IMPORT=160;
 private final Activity activity;private final SharedPreferences prefs;
 private EditText host,port,username,token,secret,config,origin;private CheckBox console,adb;private Spinner mode,format;
 private boolean syncing,checking,starting,adbReady;private TextView importedHint;private Button startButton;private TextView status,ports,summary;private Design.StatusText remoteHeading;private AlertDialog editor;
 public RemotePanel(Activity a){super(a);activity=a;prefs=a.getSharedPreferences("remote",0);setOrientation(VERTICAL);
  LinearLayout row=new LinearLayout(a);addView(row,new LayoutParams(-1,-2));LinearLayout left=Design.column(a),right=Design.column(a);Design.card(left);Design.card(right);row.addView(left,new LayoutParams(0,-2,1));LayoutParams rp=new LayoutParams(0,-2,1);rp.leftMargin=dp(18);row.addView(right,rp);
  remoteHeading=new Design.StatusText(a,"内网穿透",28);left.addView(remoteHeading);left.addView(Design.text(a,"在其他网络访问车机网页和无线 ADB",19));status=Design.text(a,RemoteService.status,23);status.setTextColor(Design.ACCENT);left.addView(status);summary=Design.text(a,"",20);left.addView(summary);console=new CheckBox(a);Design.toggle(console);console.setChecked(prefs.getBoolean("console",true));left.addView(console);adb=new CheckBox(a);Design.toggle(adb);adb.setChecked(prefs.getBoolean("adb",false));left.addView(adb);console.setOnCheckedChangeListener((v,on)->{if(!syncing)prefs.edit().putBoolean("console",on).apply();});adb.setOnCheckedChangeListener((v,on)->{if(!syncing)prefs.edit().putBoolean("adb",on).apply();});importedHint=Design.text(a,"按导入配置运行",20);left.addView(importedHint);Button startRemote=Design.button(a,"启动远程连接",this::start);startButton=startRemote;Design.actionColor(startRemote,true);Button stop=Design.button(a,"停止连接",()->RemoteService.stop(a));Design.actionColor(stop,false);buttonRow(left,startRemote,stop);buttonRow(left,Design.button(a,"服务器配置",()->openConfig()),Design.button(a,"查看日志",()->showLogs()));
  right.addView(Design.text(a,"服务端口与访问入口",26));ports=Design.text(a,"",20);ports.setTextIsSelectable(true);right.addView(ports);Design.addButton(right,Design.button(a,"复制电脑端连接配置",()->{try{if(prefs.getInt("mode",0)!=0)throw new IllegalArgumentException("第三方服务的电脑连接方式以服务商配置为准");String value=RemoteConfig.visitor(prefs.getString("host",""),RemoteConfig.port(prefs.getString("port","7000")),prefs.getString("token",""),prefs.getString("secret",""),prefs.getBoolean("console",true),prefs.getBoolean("adb",false),prefs.getString("user",""));PhoneCompanion.copy(a,"电脑端连接配置",value,true);Toast.makeText(a,"已复制，电脑保存为 visitor.toml 后运行 frpc",1).show();}catch(Exception e){Toast.makeText(a,UserMessages.explain(e),1).show();}}));right.addView(Design.text(a,"选择需要的通道后点击启动，星匣会准备对应服务。\n网页回传不要求开启无线 ADB。\n手机助手需要与车机连接同一网络。",19));refresh();
 }
 public void enter(){if(checking)return;checking=true;refresh();new Thread(()->{RootAccess.check(activity,false);boolean ready=LocalAdb.available();activity.runOnUiThread(()->{checking=false;adbReady=ready;refresh();});},"remote-capabilities").start();}
 private void start(){if(starting||checking)return;try{if(RemoteService.running)throw new IllegalStateException("远程连接已在运行");if(prefs.getString("config","").trim().isEmpty())throw new IllegalArgumentException("请先填写并保存服务器配置");}catch(Exception e){Toast.makeText(activity,UserMessages.explain(e),1).show();return;}
  boolean own=prefs.getInt("mode",0)==0,web=console.isChecked(),deviceAdb=adb.isChecked(),wantRoot=RootAccess.available();if(own&&!web&&!deviceAdb){Toast.makeText(activity,"请至少选择一个远程服务",1).show();return;}starting=true;refresh();new Thread(()->{String failure="";boolean ready=false;try{if(own){RootAccess.check(activity,false);if(deviceAdb){ready=LocalAdb.available();if(!ready){if(!RootAccess.available())throw new IOException("请提权后再开启远程 ADB");CommandRunner runner=RootAccess.runner(activity);CommandRunner.Result result;try{synchronized(AdbControl.LOCK){result=runner.execute(AdbControl.ensureLocal(),true,10);}}finally{runner.close();}if(result.exit!=0||result.timedOut||!result.error.isEmpty())throw new IOException("无线 ADB 准备失败："+UserMessages.explain(result.error.isEmpty()?result.stderr:result.error));ready=LocalAdb.available();if(!ready)throw new IOException("ADB 尚未就绪，请重新检测");}}
   if(web&&ConsoleService.server==null){if(wantRoot&&!RootAccess.available())throw new IOException("Root 授权已失效，请重新授权后再启动");ConsoleService.startSession(activity,ConsoleService.lanHost(activity),wantRoot);}
   prefs.edit().putBoolean("console",web).putBoolean("adb",deviceAdb).apply();refreshOwnConfig();}
   RemoteService.start(activity);
  }catch(Exception e){failure=UserMessages.explain(e);}String error=failure;boolean detected=ready;activity.runOnUiThread(()->{starting=false;adbReady=detected;refresh();if(!error.isEmpty())Toast.makeText(activity,error,1).show();});},"prepare-remote").start();}
 private void buttonRow(LinearLayout target,Button first,Button second){LinearLayout row=new LinearLayout(activity);target.addView(row);LayoutParams p=new LayoutParams(0,dp(54),1);p.setMargins(0,dp(6),dp(10),dp(6));row.addView(first,p);LayoutParams q=new LayoutParams(0,dp(54),1);q.setMargins(0,dp(6),0,dp(6));row.addView(second,q);}
 private int dp(int n){return Design.dp(activity,n);}
 private int webPort(){return ConsoleService.webPort();}
 private void refreshOwnConfig(){String value=RemoteConfig.client(prefs.getString("host",""),RemoteConfig.port(prefs.getString("port","7000")),prefs.getString("token",""),prefs.getString("secret",""),"127.0.0.1",webPort(),prefs.getBoolean("console",true),prefs.getBoolean("adb",false),prefs.getString("user",""));prefs.edit().putString("config",value).putString("format","toml").apply();}
 private EditText field(LinearLayout body,String label,String key,String def,boolean sensitive){body.addView(Design.text(activity,label,19));EditText e=new EditText(activity);e.setSingleLine(true);Design.input(e,"远程 → "+label,sensitive);e.setHint(label);e.setText(prefs.getString(key,def));body.addView(e,new LayoutParams(-1,dp(52)));if(key.equals("host")||key.equals("port")||key.equals("origin"))NumberPad.attach(e);if(sensitive){CheckBox reveal=new CheckBox(activity);reveal.setText("显示"+label);Design.toggle(reveal);body.addView(reveal);reveal.setOnCheckedChangeListener((v,on)->{e.setTransformationMethod(on?null:android.text.method.PasswordTransformationMethod.getInstance());e.setSelection(e.getText().length());});}return e;}
 private void openConfig(){if(RemoteService.running){Toast.makeText(activity,"请先停止远程连接再修改配置",1).show();return;}LinearLayout outer=Design.column(activity);outer.setPadding(dp(24),dp(8),dp(24),dp(16));mode=new Spinner(activity);mode.setAdapter(new UiAdapter(activity,new String[]{"自建服务器 · 私密连接","第三方服务 · 导入配置"}));outer.addView(mode);LinearLayout own=Design.column(activity),imported=Design.column(activity);outer.addView(own);outer.addView(imported);
  LinearLayout ownRow=new LinearLayout(activity);own.addView(ownRow);LinearLayout server=Design.column(activity),credentials=Design.column(activity);ownRow.addView(server,new LayoutParams(0,-2,1));LayoutParams cp=new LayoutParams(0,-2,1);cp.leftMargin=dp(24);ownRow.addView(credentials,cp);host=field(server,"服务器地址","host","",false);port=field(server,"服务器端口","port","7000",false);username=field(credentials,"用户名（可选）","user","",false);username.setHint("服务商提供则填写，否则留空");token=field(credentials,"Token","token","",true);String generated="";if(prefs.getString("secret","").isEmpty()){byte[] bytes=new byte[16];new SecureRandom().nextBytes(bytes);StringBuilder b=new StringBuilder();for(byte n:bytes)b.append(String.format(java.util.Locale.US,"%02x",n&255));generated=b.toString();}secret=field(credentials,"穿透密钥","secret",generated,true);
  imported.addView(Design.text(activity,"配置格式",19));format=new Spinner(activity);format.setAdapter(new UiAdapter(activity,new String[]{"TOML","YAML","JSON"}));String type=prefs.getString("format","toml");format.setSelection(type.equals("yaml")?1:type.equals("json")?2:0);imported.addView(format);origin=field(imported,"远程网页地址","origin","http://127.0.0.1:8875",false);imported.addView(Design.text(activity,"服务器映射端口以配置为准；填写服务商提供的网页根地址。",18));config=new EditText(activity);Design.input(config,"远程 → frpc 配置",false);config.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);config.setTransformationMethod(android.text.method.PasswordTransformationMethod.getInstance());config.setGravity(android.view.Gravity.TOP);config.setHint("使用顶部手机助手发送配置，或从文件导入");config.setText(prefs.getString("config",""));imported.addView(config,new LayoutParams(-1,dp(150)));CheckBox show=new CheckBox(activity);show.setText("显示配置内容（含密钥）");Design.toggle(show);imported.addView(show);show.setOnCheckedChangeListener((v,on)->config.setTransformationMethod(on?null:android.text.method.PasswordTransformationMethod.getInstance()));Design.addButton(imported,Design.button(activity,"从文件导入配置",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);activity.startActivityForResult(i,IMPORT);}));mode.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,android.view.View v,int n,long id){own.setVisibility(n==0?0:8);imported.setVisibility(n==1?0:8);}});mode.setSelection(prefs.getInt("mode",0));outer.addView(Design.text(activity,"先点击需要填写的输入框，再用手机助手发送 Token、密钥或配置。",18));
  editor=new AlertDialog.Builder(activity).setTitle("远程服务器配置").setView(Design.scroll(activity,outer)).setPositiveButton("保存配置",null).setNegativeButton("取消",null).create();editor.setOnShowListener(d->{Design.dialog(editor);editor.getWindow().setLayout(dp(1100),-2);editor.getWindow().setSoftInputMode(android.view.WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);editor.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{save();editor.dismiss();refresh();Toast.makeText(activity,"配置已保存",0).show();}catch(Exception e){Toast.makeText(activity,UserMessages.explain(e),1).show();}});});editor.setOnKeyListener((d,key,event)->key==android.view.KeyEvent.KEYCODE_BACK&&event.getAction()==android.view.KeyEvent.ACTION_UP&&NumberPad.dismiss());editor.setOnDismissListener(d->NumberPad.dismiss());editor.show();
 }
 private void save(){if(RemoteService.running)throw new IllegalStateException("请先停止远程连接");boolean own=mode.getSelectedItemPosition()==0;String value=own?RemoteConfig.client(host.getText().toString().trim(),RemoteConfig.port(port.getText().toString().trim()),token.getText().toString(),secret.getText().toString(),"127.0.0.1",webPort(),prefs.getBoolean("console",true)||!prefs.getBoolean("adb",false),prefs.getBoolean("adb",false),username.getText().toString().trim()):config.getText().toString();if(value.trim().isEmpty()||value.length()>65536)throw new IllegalArgumentException("请填写配置，最多 65536 个字符");String access=own?"http://127.0.0.1:8875":origin.getText().toString().trim();java.net.URI uri=java.net.URI.create(access);if(!("http".equals(uri.getScheme())||"https".equals(uri.getScheme()))||uri.getHost()==null||uri.getUserInfo()!=null||uri.getQuery()!=null||uri.getFragment()!=null||!(uri.getPath().isEmpty()||uri.getPath().equals("/")))throw new IllegalArgumentException("请填写 http(s)://域名:端口 格式的网页根地址");prefs.edit().putString("origin",access).putString("host",host.getText().toString().trim()).putString("port",port.getText().toString().trim()).putString("user",username.getText().toString().trim()).putString("token",token.getText().toString()).putString("secret",secret.getText().toString()).putString("config",value).putString("format",own?"toml":new String[]{"toml","yaml","json"}[format.getSelectedItemPosition()]).putInt("mode",mode.getSelectedItemPosition()).apply();}
 private void showLogs(){TextView log=Design.text(activity,RemoteService.log.isEmpty()?"暂无日志":RemoteService.log,18);log.setTextIsSelectable(true);log.setPadding(dp(20),dp(16),dp(20),dp(16));ScrollView scroll=new ScrollView(activity);scroll.addView(log);AlertDialog dialog=new AlertDialog.Builder(activity).setTitle("远程连接日志").setView(scroll).setPositiveButton("关闭",null).setNeutralButton("刷新",null).create();dialog.setOnShowListener(d->{Design.dialog(dialog);dialog.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->log.setText(RemoteService.log.isEmpty()?"暂无日志":RemoteService.log));});dialog.show();}
 public void importUri(Uri uri){if(config==null)return;try(InputStream in=activity.getContentResolver().openInputStream(uri)){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>262144)throw new IOException("配置文件过大");}String value=out.toString("UTF-8");if(value.length()>65536)throw new IOException("配置最多 65536 个字符");config.setText(value);mode.setSelection(1);Toast.makeText(activity,"已载入，选择格式后保存",1).show();}catch(Exception e){Toast.makeText(activity,"导入失败："+UserMessages.explain(e),1).show();}}
 private static void stable(TextView view,String text){if(!view.getText().toString().equals(text))view.setText(text);}
 public void refresh(){boolean own=prefs.getInt("mode",0)==0,locked=RemoteService.running||starting||checking;syncing=true;console.setVisibility(own?VISIBLE:GONE);adb.setVisibility(own?VISIBLE:GONE);importedHint.setVisibility(own?GONE:VISIBLE);console.setEnabled(!locked);adb.setEnabled(!locked&&(adbReady||RootAccess.available()));console.setChecked(prefs.getBoolean("console",true));adb.setChecked(prefs.getBoolean("adb",false)&&(RemoteService.running||adbReady||RootAccess.available()));stable(console,"打开网页回传 - "+((ConsoleService.server==null?RootAccess.available():ConsoleService.root)?"Root":"无 Root"));stable(adb,checking?"远程ADB · 正在检测":adbReady||RootAccess.available()?"远程ADB":"远程ADB · 请提权");startButton.setEnabled(!locked);syncing=false;remoteHeading.state(RemoteService.running);if(!status.getText().toString().equals(RemoteService.status))status.setText(RemoteService.status);String value=prefs.getString("host","").isEmpty()&&prefs.getString("config","").isEmpty()?"尚未配置服务器":prefs.getInt("mode",0)==0?"自建服务器 · "+prefs.getString("host","")+":"+prefs.getString("port","7000"):"第三方配置 · "+prefs.getString("format","toml").toUpperCase(java.util.Locale.US);if(!summary.getText().toString().equals(value))summary.setText(value);String text="车机本地端口\n命令网页  "+webPort()+(ConsoleService.server==null?"（未启动）":"（运行中）")+"\n无线 ADB  5555\n\n"+(prefs.getInt("mode",0)==0?"内网穿透访问入口\n网页  http://127.0.0.1:8875\nADB  127.0.0.1:8556":"第三方服务器入口\n网页  "+prefs.getString("origin","")+"\nADB  使用配置中的映射端口");if(!ports.getText().toString().equals(text))ports.setText(text);}
}
