package com.e02.rootconsole;
/** Generated private STCP tunnels require a matching computer-side visitor. */
public final class RemoteConfig {
 public static String quoted(String s){return "\""+s.replace("\\","\\\\").replace("\"","\\\"").replace("\n","\\n").replace("\r","\\r").replace("\t","\\t")+"\"";}
 public static int port(String s){try{int n=Integer.parseInt(s);if(n>0&&n<=65535)return n;}catch(Exception ignored){}throw new IllegalArgumentException("端口须为 1–65535");}
 private static String header(String host,int port,String token){if(host==null||!host.matches("[A-Za-z0-9][A-Za-z0-9.-]{0,252}"))throw new IllegalArgumentException("请填写服务器 IP 或域名，不含 http://、https:// 或端口");if(token.trim().isEmpty())throw new IllegalArgumentException("请填写服务器 Token");return "serverAddr = "+quoted(host)+"\nserverPort = "+port+"\nauth.method = \"token\"\nauth.token = "+quoted(token)+"\ntransport.tls.enable = true\n";}
 public static String client(String host,int port,String token,String secret,String local,boolean console,boolean adb){return client(host,port,token,secret,local,8875,console,adb);}
 public static String client(String host,int port,String token,String secret,String local,int webPort,boolean console,boolean adb){return client(host,port,token,secret,local,webPort,console,adb,"");}
 public static String client(String host,int port,String token,String secret,String local,int webPort,boolean console,boolean adb,String user){if(secret.length()<16)throw new IllegalArgumentException("穿透密钥至少 16 位");if(!console&&!adb)throw new IllegalArgumentException("请至少选择一个远程服务");if(webPort<1||webPort>65535)throw new IllegalArgumentException("网页端口无效");String config=header(host,port,token)+username(user)+"loginFailExit = false\nlog.to = \"console\"\nlog.level = \"info\"\n";if(console)config+=proxy("e02-console",secret,AdbControl.ipv4(local),webPort);if(adb)config+=proxy("e02-adb",secret,"127.0.0.1",5555);return config;}
 private static String username(String user){String value=user==null?"":user.trim();if(value.length()>128||value.indexOf('\n')>=0||value.indexOf('\r')>=0||value.indexOf('\u0000')>=0)throw new IllegalArgumentException("用户名须为单行，最多 128 个字符");return value.isEmpty()?"":"user = "+quoted(value)+"\n";}
 private static String proxy(String name,String secret,String local,int port){return "\n[[proxies]]\nname = "+quoted(name)+"\ntype = \"stcp\"\nsecretKey = "+quoted(secret)+"\nlocalIP = "+quoted(local)+"\nlocalPort = "+port+"\n";}
 public static String visitor(String host,int port,String token,String secret,boolean console,boolean adb){return visitor(host,port,token,secret,console,adb,"");}
 public static String visitor(String host,int port,String token,String secret,boolean console,boolean adb,String user){String config=header(host,port,token)+username(user);if(console)config+=visitor("e02-console",secret,8875);if(adb)config+=visitor("e02-adb",secret,8556);return config;}
 private static String visitor(String name,String secret,int port){return "\n[[visitors]]\nname = "+quoted(name+"-visitor")+"\ntype = \"stcp\"\nserverName = "+quoted(name)+"\nsecretKey = "+quoted(secret)+"\nbindAddr = \"127.0.0.1\"\nbindPort = "+port+"\n";}
}
