package com.e02.rootconsole;
import android.app.*;
import android.content.*;
import android.content.pm.*;
import android.os.*;
import java.io.*;
import java.net.*;
import java.security.*;
import org.json.JSONObject;
/** One process-wide update task; foreground service keeps downloads alive. */
public class UpdateService extends Service {
 public static volatile String message="尚未检查更新",version="",notes="",downloadUrl="",hash="",proxy="";
 public static volatile long bytes,size,remoteCode;
 public static volatile boolean busy,downloading,ready,available,manual;
 private static volatile boolean cancelled;private static volatile HttpURLConnection active;
 private static final int NOTIFICATION=21;
 private static synchronized boolean begin(){if(busy)return false;busy=true;cancelled=false;return true;}
 private static long installed(Context c)throws Exception{return c.getPackageManager().getPackageInfo(c.getPackageName(),0).getLongVersionCode();}
 private static HttpURLConnection connect(String address)throws Exception{URL u=new URL(address);for(int i=0;i<6;i++){if(cancelled)throw new IOException("已取消");if(!u.getProtocol().equals("https"))throw new IOException("更新线路必须使用 HTTPS");HttpURLConnection c=(HttpURLConnection)u.openConnection();active=c;c.setConnectTimeout(15000);c.setReadTimeout(20000);c.setInstanceFollowRedirects(false);c.setRequestProperty("User-Agent","E02-StarBox");c.setRequestProperty("Cache-Control","no-cache");int status=c.getResponseCode();if(status>=300&&status<=399){String next=c.getHeaderField("Location");c.disconnect();if(next==null)throw new IOException("线路返回无效跳转");u=new URL(u,next);continue;}if(status!=200){c.disconnect();throw new IOException("线路返回 HTTP "+status);}return c;}throw new IOException("线路跳转过多");}
 public static void check(Context context,boolean user){if(!RiskNotice.accepted(context))return;Context c=context.getApplicationContext();if(!begin())return;manual=user;message="正在检查更新…";new Thread(()->{HttpURLConnection conn=null;try{String route=UpdatePolicy.normalize(c.getSharedPreferences("updates",0).getString("proxy",""));conn=connect(UpdatePolicy.url(route,UpdatePolicy.MANIFEST));ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=conn.getInputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(cancelled)throw new IOException("已取消");out.write(b,0,n);if(out.size()>65536)throw new IOException("版本文件过大");}}JSONObject j=new JSONObject(out.toString("UTF-8"));long code=j.getLong("versionCode");String name=j.getString("version"),url=j.getString("apk"),sha=j.getString("sha256");long length=j.getLong("size");UpdatePolicy.url(route,url);if(!sha.matches("[a-fA-F0-9]{64}")||length<1024||length>50*1024*1024)throw new IOException("版本文件格式无效");boolean changed=remoteCode!=code||!hash.equalsIgnoreCase(sha);if(changed){ready=false;bytes=0;}version=name;remoteCode=code;downloadUrl=url;hash=sha;size=length;notes=j.optString("notes","");proxy=route;available=UpdatePolicy.newer(code,installed(c));if(!available)ready=false;message=available?"发现新版本 "+version:"已是最新版";}catch(Exception e){message="检查失败："+UserMessages.explain(e)+"。可在设置中更换线路后重试。";}finally{if(conn!=null)conn.disconnect();active=null;busy=false;}},"starbox-update-check").start();}
 public static void cancel(){cancelled=true;HttpURLConnection c=active;if(c!=null)c.disconnect();}
 public static void download(Context c){if(!RiskNotice.accepted(c))return;if(!available||busy||ready)return;c.startForegroundService(new Intent(c,UpdateService.class));}
 public void onCreate(){super.onCreate();NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);nm.createNotificationChannel(new NotificationChannel("starbox-update","星匣版本更新",NotificationManager.IMPORTANCE_LOW));startForeground(NOTIFICATION,new Notification.Builder(this,"starbox-update").setSmallIcon(getApplicationInfo().icon).setContentTitle("E02星匣").setContentText("准备下载安装包…").setOngoing(true).setContentIntent(PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT)).addAction(0,"取消下载",PendingIntent.getService(this,0,new Intent(this,UpdateService.class).setAction("cancel"),PendingIntent.FLAG_UPDATE_CURRENT)).build());}
 public int onStartCommand(Intent intent,int flags,int id){if(!RiskNotice.accepted(this)){stopSelf();return START_NOT_STICKY;}if(intent!=null&&"cancel".equals(intent.getAction())){cancel();return START_NOT_STICKY;}if(!available||!begin()){if(!downloading)stopSelf();return START_NOT_STICKY;}downloading=true;startForegroundService(new Intent(this,ConsoleService.class));bytes=0;message="正在下载 "+version;final String url=downloadUrl,expectedHash=hash;final long expectedSize=size,expectedCode=remoteCode;final String route=getSharedPreferences("updates",0).getString("proxy","");new Thread(()->{File folder=new File(getFilesDir(),"updates"),part=new File(folder,"update.part"),apk=new File(folder,"update.apk");HttpURLConnection conn=null;try{if(!folder.exists()&&!folder.mkdirs())throw new IOException("无法创建下载目录");conn=connect(UpdatePolicy.url(route,url));MessageDigest digest=MessageDigest.getInstance("SHA-256");long last=0;try(InputStream in=conn.getInputStream();FileOutputStream out=new FileOutputStream(part)){byte[] buffer=new byte[16384];int n;while((n=in.read(buffer))!=-1){if(cancelled)throw new IOException("已取消下载");out.write(buffer,0,n);digest.update(buffer,0,n);bytes+=n;if(bytes>expectedSize)throw new IOException("安装包大小不匹配");if(System.currentTimeMillis()-last>500){last=System.currentTimeMillis();message="下载中 "+(bytes*100/expectedSize)+"%";((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).notify(NOTIFICATION,new Notification.Builder(this,"starbox-update").setSmallIcon(getApplicationInfo().icon).setContentTitle("E02星匣 · "+version).setContentText(message).setProgress(100,(int)(bytes*100/expectedSize),false).setOngoing(true).setContentIntent(PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT)).addAction(0,"取消下载",PendingIntent.getService(this,0,new Intent(this,UpdateService.class).setAction("cancel"),PendingIntent.FLAG_UPDATE_CURRENT)).build());}}out.getFD().sync();}StringBuilder sha=new StringBuilder();for(byte b:digest.digest())sha.append(String.format(java.util.Locale.US,"%02x",b&255));if(cancelled)throw new IOException("已取消下载");if(bytes!=expectedSize||!expectedHash.equalsIgnoreCase(sha.toString()))throw new IOException("安装包完整性校验失败");verify(part,expectedCode);if(apk.exists()&&!apk.delete())throw new IOException("无法替换旧安装包");if(!part.renameTo(apk))throw new IOException("无法保存安装包");ready=true;message="下载完成，点击安装 "+version;}catch(Exception e){ready=false;message=cancelled?"下载已取消，可点击新版提示重新下载":"下载失败："+UserMessages.explain(e)+"。点击新版提示重试。";}finally{if(conn!=null)conn.disconnect();active=null;if(part.exists())part.delete();downloading=false;busy=false;stopForeground(true);stopSelf();}},"starbox-update-download").start();return START_NOT_STICKY;}
 private void verify(File f,long expected)throws Exception{PackageManager pm=getPackageManager();PackageInfo apk=pm.getPackageArchiveInfo(f.getAbsolutePath(),PackageManager.GET_SIGNATURES),local=pm.getPackageInfo(getPackageName(),PackageManager.GET_SIGNATURES);if(apk==null||!getPackageName().equals(apk.packageName)||apk.getLongVersionCode()!=expected||expected<=local.getLongVersionCode())throw new IOException("安装包版本或包名不匹配");if(apk.signatures==null||local.signatures==null||!java.util.Arrays.equals(apk.signatures,local.signatures))throw new IOException("安装包签名不匹配");}
 public void onDestroy(){if(downloading)cancel();super.onDestroy();}public IBinder onBind(Intent i){return null;}
}
